#include "core/Document.h"
#include "effects/Adjustments.h"
#include "effects/LayerEffects.h"
#include "filters/PixelFilters.h"
#include "layers/LayerOperations.h"
#include "graphics/GrowingBrushSession.h"
#include <QJsonDocument>
#include <QJsonObject>
#include <cmath>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
Layer image(std::string id,int w,int h,Pixel value){Layer l;l.id=id;l.raster=Raster::filled(w,h,value);l.transform={0,0,double(w),double(h),0,false,false,Transform::Sampling::Nearest};return l;}
std::string settings(const char* kind,const char* key,double value){auto o=QJsonDocument::fromJson(QByteArray::fromStdString(effects::defaultAdjustmentJson(kind))).object();o[key]=value;return QJsonDocument(o).toJson(QJsonDocument::Compact).toStdString();}
void same(const Raster& a,const Raster& b){require(a.width==b.width&&a.height==b.height,"dimensions differ");for(int y=0;y<a.height;++y)for(int x=0;x<a.width;++x)require(a.pixel(x,y)==b.pixel(x,y),"pixels differ");}
}
int main(){int count=0;auto test=[&](const char* name,auto run){try{run();++count;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& error){std::cerr<<"FAIL "<<name<<": "<<error.what()<<'\n';throw;}};
try{
 test("24 modes preserve premultiplication and opacity",[]{require(blendNames.size()==24,"blend count");for(size_t i=0;i<blendNames.size();++i){auto p=blendPixel({60,30,10,100},{20,80,40,120},Blend(i));require(p.a==173&&p.r<=p.a&&p.g<=p.a&&p.b<=p.a,"invalid alpha blend");}require(blendPixel({128,128,128,255},{64,64,64,255},Blend::Subtract).r==64,"subtract formula");require(blendPixel({64,64,64,255},{128,128,128,255},Blend::Divide).r==128,"divide formula");require(blendPixel({128,128,128,255},{128,128,128,255},Blend::LinearDodge).r==255,"add formula");});
 test("nested folder opacity follows pass through",[]{Document d;d.width=d.height=1;Layer f;f.id="folder";f.group=true;f.opacity=.5;Layer inner=f;inner.id="inner";inner.parentId=f.id;inner.opacity=.5;auto l=image("pixels",1,1,{255,0,0,255});l.parentId=inner.id;d.layers={f,inner,l};require(SoftwareRenderer().render(d,0,0,1,1)->pixel(0,0)==Pixel{64,0,0,64},"nested opacity wrong");});
 test("six effects are renderable editable and masked",[]{for(const char* key:{"stroke","shadow","colorOverlay","innerShadow","outerGlow","innerGlow"}){Document d;d.width=d.height=20;auto l=image("pixels",6,6,{255,0,0,255});l.transform.x=l.transform.y=7;QJsonObject value{{"size",2},{"distance",2},{"blur",1},{"red",0},{"green",1},{"blue",0},{"opacity",1}};l.effectsJson=QJsonDocument(QJsonObject{{key,value}}).toJson(QJsonDocument::Compact).toStdString();effects::validateLayerEffectsJson(l.effectsJson);d.layers={l};auto shown=SoftwareRenderer().render(d,0,0,20,20);auto plain=d;plain.layers[0].effectsJson.clear();require(shown->rgba()!=SoftwareRenderer().render(plain,0,0,20,20)->rgba(),"effect invisible");value["enabled"]=false;d.layers[0].effectsJson=QJsonDocument(QJsonObject{{key,value}}).toJson(QJsonDocument::Compact).toStdString();same(*SoftwareRenderer().render(d,0,0,20,20),*SoftwareRenderer().render(plain,0,0,20,20));auto m=std::make_shared<GrayRaster>();m->width=m->height=1;m->pixels={0};l.mask=Mask{m};d.layers={l};auto masked=SoftwareRenderer().render(d,0,0,20,20);for(int y=0;y<20;++y)for(int x=0;x<20;++x)require(masked->pixel(x,y).a==0,"effect ignored silhouette mask");}});
 test("effect transform and cached viewport halo",[]{Document d;d.width=d.height=30;auto l=image("pixels",2,4,{255,0,0,255});l.transform={10,10,4,8,90,false,false,Transform::Sampling::Nearest};l.effectsJson=R"({"stroke":{"size":2,"green":1}})";d.layers={l};CompositeCache cache;auto a=cache.render(d),b=SoftwareRenderer().render(d,0,0,30,30);same(*a,*b);require(a->pixel(8,12).a>0,"effect halo clipped");d.layers[0].effectsJson=R"({"stroke":{"size":3,"blue":1}})";same(*cache.render(d),*SoftwareRenderer().render(d,0,0,30,30));});
 test("blur adjustments retain halo across tile and export regions",[]{for(const char* kind:{"Gaussian Blur","Motion Blur"}){Document d;d.width=44;d.height=24;auto l=image("pixels",44,24,{});Pixel p{255,255,255,255};l.raster=l.raster->replacing(22,12,1,1,&p,1);Layer a;a.id="blur";a.adjustmentJson=settings(kind,kind[0]=='G'?"blurRadius":"motionDistance",4);d.layers={l,a};auto full=SoftwareRenderer().render(d,0,0,44,24);auto tile=SoftwareRenderer().render(d,20,10,7,7);for(int y=0;y<7;++y)for(int x=0;x<7;++x)require(tile->pixel(x,y)==full->pixel(x+20,y+10),"blur seam");require(full->pixel(21,12).a>0,"blur did not spread");}});
 test("new color adjustments and anchored noise",[]{auto red=Raster::filled(2,2,{255,0,0,255});auto bw=effects::applyAdjustment(red,effects::defaultAdjustmentJson("Black & White"));require(bw->pixel(0,0)==Pixel{102,102,102,255},"B&W red weight");auto inverted=effects::applyAdjustment(red,effects::defaultAdjustmentJson("Invert"));require(inverted->pixel(0,0)==Pixel{0,255,255,255},"invert");same(*red,*effects::applyAdjustment(red,effects::defaultAdjustmentJson("Color Balance")));auto whole=Raster::filled(30,20,{90,90,90,128}),tile=Raster::filled(8,7,{90,90,90,128});auto json=effects::defaultAdjustmentJson("Add Noise");auto a=effects::applyAdjustment(whole,json),b=effects::applyAdjustment(tile,json,nullptr,{12,8,1});for(int y=0;y<7;++y)for(int x=0;x<8;++x)require(a->pixel(x+12,y+8)==b->pixel(x,y),"noise pattern shifts on tile origin");});
 test("finishing filters preserve alpha selection and zero amount",[]{auto source=Raster::filled(18,12,{80,40,20,128});GrayRaster selection;selection.width=18;selection.height=12;selection.pixels.assign(216,0);for(auto kind:{filters::Kind::Vignette,filters::Kind::BloomGlow,filters::Kind::TonalContrast}){filters::Settings settings;settings.vignetteAmount=settings.bloomAmount=settings.tonalAmount=0;same(*source,*filters::runPixels(kind,*source,settings,1,0));settings.vignetteAmount=settings.bloomAmount=settings.tonalAmount=75;same(*source,*filters::runPixels(kind,*source,settings,1,0,&selection));auto out=filters::runPixels(kind,*source,settings,1,0);for(int y=0;y<12;++y)for(int x=0;x<18;++x)require(out->pixel(x,y).a==128,"finishing filter changed alpha");}});
 test("effects clipping and merge preserve the composite",[]{Document d;d.width=d.height=28;auto base=image("base",10,10,{128,0,0,128});base.transform.x=base.transform.y=9;auto child=image("child",28,28,{0,255,0,255});child.maskSourceId=base.id;base.effectsJson=R"({"stroke":{"size":3,"blue":1,"opacity":0.5}})";d.layers={base,child};auto before=SoftwareRenderer().render(d,0,0,28,28);require(before->pixel(6,12).a>0&&before->pixel(6,12).g>0,"clipping ignored effect silhouette");auto merged=layers::merge(d,{{"base","child"},"child"},SoftwareRenderer());require(merged.changed&&merged.document.layers.size()==1&&merged.document.layers[0].effectsJson.empty(),"merge did not bake effects");same(*before,*SoftwareRenderer().render(merged.document,0,0,28,28));
 auto preview=SoftwareRenderer().renderScaled(d,0,0,14,14,2);for(int y=0;y<14;++y)for(int x=0;x<14;++x)require(preview->pixel(x,y)==before->pixel(x*2+1,y*2+1),"preview effect placement differs from full resolution");});
 test("painting effects preview equals committed grown image and mask",[]{for(bool mask:{false,true}){Document d;d.width=40;d.height=30;auto subject=image("subject",8,8,{255,0,0,255});subject.transform.x=12;subject.transform.y=8;subject.effectsJson=R"({"stroke":{"size":2,"green":1},"shadow":{"distance":2,"blur":1}})";if(mask)subject.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{255}})};d.layers={subject};graphics::BrushSessionSettings settings;settings.radius=3;settings.hardness=1;settings.color=mask?std::array<uint8_t,3>{0,0,0}:std::array<uint8_t,3>{0,0,255};graphics::GrowingBrushSession stroke(subject,settings,40,30,{},{},mask,1000000,{},true);stroke.begin(mask?Point{13,10}:Point{7,10});auto snapshot=stroke.commit();auto preview=SoftwareRenderer(snapshot->renderPreview()).render(d,0,0,40,30);d.layers[0]=snapshot->materializeLayer();same(*preview,*SoftwareRenderer().render(d,0,0,40,30));}});
 test("effects invalid parameters rejected",[]{bool rejected=false;try{effects::validateLayerEffectsJson(R"({"stroke":{"size":501}})");}catch(...){rejected=true;}require(rejected,"invalid effect accepted");});
}catch(...){return 1;}std::cout<<count<<" rendering v1.2.11 checks passed\n";return 0;}
