#include "CameraRawPanel.h"
#include "PropertyControls.h"
#include "graphics/Downsample.h"
#include "effects_tools/CurveMath.h"
#include <QDialog>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFormLayout>
#include <QGridLayout>
#include <QScrollArea>
#include <QTabWidget>
#include <QLabel>
#include <QPainter>
#include <QPainterPath>
#include <QConicalGradient>
#include <QRadialGradient>
#include <QMouseEvent>
#include <QCheckBox>
#include <QComboBox>
#include <QPushButton>
#include <QDialogButtonBox>
#include <QFutureWatcher>
#include <QTimer>
#include <QSettings>
#include <QApplication>
#include <QtConcurrent/QtConcurrentRun>
#include <atomic>
#include <cmath>
#include <numbers>
namespace compositor {
namespace {
QImage qimage(const Raster& raster){auto data=raster.rgba();return QImage(data.data(),raster.width,raster.height,raster.width*4,QImage::Format_RGBA8888_Premultiplied).copy();}
class ImageView final:public QWidget {
    QImage image_;QRectF draw_;std::optional<Point> guideStart_;double zoom_{1};std::optional<Point> targetPoint_;double targetY_{};
public:
    std::function<void(Point)> sampled;
    std::function<void(Point,Point)> guided;
    std::function<void(Point,double,Qt::KeyboardModifiers,bool)> targeted;
    std::vector<std::pair<Point,Point>> guides;
    bool drawGuides{},targeting{};
    ImageView(){setObjectName("cameraRawPreview");setMinimumSize(260,200);setSizePolicy(QSizePolicy::Expanding,QSizePolicy::Expanding);setAccessibleName("Camera Raw image preview");}
    void setImage(QImage image){image_=std::move(image);update();}
    const QImage& image()const{return image_;}
protected:
    void paintEvent(QPaintEvent*)override{QPainter p(this);p.fillRect(rect(),QColor("#181b20"));if(image_.isNull())return;QSizeF size=image_.size();size.scale(QSizeF(width(),height())*zoom_,Qt::KeepAspectRatio);draw_={(width()-size.width())/2,(height()-size.height())/2,size.width(),size.height()};p.setRenderHint(QPainter::SmoothPixmapTransform);p.drawImage(draw_,image_);p.setPen(QPen(QColor("#4ca7ef"),2));for(const auto& [a,b]:guides)p.drawLine(QPointF(draw_.x()+a.x*draw_.width(),draw_.y()+(1-a.y)*draw_.height()),QPointF(draw_.x()+b.x*draw_.width(),draw_.y()+(1-b.y)*draw_.height()));}
    std::optional<Point> point(QPointF p)const{if(draw_.isEmpty()||!draw_.contains(p))return {};return Point{(p.x()-draw_.x())/draw_.width(),(p.y()-draw_.y())/draw_.height()};}
    void mousePressEvent(QMouseEvent* e)override{if(e->button()!=Qt::LeftButton)return;auto p=point(e->position());if(!p)return;if(drawGuides)guideStart_=Point{p->x,1-p->y};else if(targeting){targetPoint_=*p;targetY_=e->position().y();if(targeted)targeted(*p,0,e->modifiers(),true);}else if(sampled)sampled(*p);}
    void mouseMoveEvent(QMouseEvent* e)override{if(targetPoint_&&targeted)targeted(*targetPoint_,targetY_-e->position().y(),e->modifiers(),false);}
    void mouseReleaseEvent(QMouseEvent* e)override{targetPoint_.reset();if(guideStart_){auto end=point(e->position());if(end&&guided)guided(*guideStart_,{end->x,1-end->y});guideStart_.reset();}}
    void wheelEvent(QWheelEvent* e)override{zoom_=std::clamp(zoom_*std::pow(1.001,e->angleDelta().y()),.25,8.);update();e->accept();}
};
class Scope final:public QWidget {
    QImage image_;bool vector_{};
public:
    Scope(){setFixedHeight(112);setAccessibleName("Camera Raw histogram");}
    void setImage(const QImage& image){image_=image;update();}void setVector(bool value){vector_=value;update();}
protected:
    void paintEvent(QPaintEvent*)override{QPainter p(this);p.fillRect(rect(),QColor("#15171c"));if(image_.isNull())return;std::array<std::array<int,256>,3> bins{};std::array<int,4096> scope{};int peak=1;for(int y=0;y<image_.height();++y)for(int x=0;x<image_.width();++x){auto c=image_.pixelColor(x,y);if(!c.alpha())continue;if(vector_){double hue=c.hsvHueF()*2*std::numbers::pi,s=c.hsvSaturationF();int xx=std::clamp(int((.5+std::cos(hue)*s*.48)*64),0,63),yy=std::clamp(int((.5+std::sin(hue)*s*.48)*64),0,63);peak=std::max(peak,++scope[size_t(yy)*64+xx]);}else{++bins[0][size_t(c.red())];++bins[1][size_t(c.green())];++bins[2][size_t(c.blue())];}}
        if(vector_){const auto side=std::min(width(),height())-6;const auto left=(width()-side)/2.;p.setPen(QColor("#444951"));p.drawEllipse(QRectF(left,3,side,side));for(int y=0;y<64;++y)for(int x=0;x<64;++x)if(scope[size_t(y)*64+x]){p.setPen(QColor(125,220,170,std::clamp(int(40+215*std::sqrt(scope[size_t(y)*64+x]/double(peak))),0,255)));p.drawPoint(QPointF(left+x*side/64.,3+y*side/64.));}return;}for(const auto& bin:bins)for(int count:bin)peak=std::max(peak,count);const QColor colors[]{QColor(239,102,104,155),QColor(83,216,145,155),QColor(86,157,244,155)};for(size_t c=0;c<3;++c){QPainterPath path;path.moveTo(0,height());for(int i=0;i<256;++i)path.lineTo(i*width()/255.,height()-std::sqrt(bins[c][size_t(i)]/double(peak))*(height()-4));path.lineTo(width(),height());p.fillPath(path,colors[c]);}}
};
class CurveView final:public QWidget {
public:
    std::vector<Point>* points{};std::function<void()> changed;int dragging{-1};
    CurveView(){setMinimumHeight(150);setAccessibleName("Camera Raw point curve; click to add, drag to move, double click to remove");}
protected:
    Point point(QPointF p){return {std::clamp(p.x()/width()*255,0.,255.),std::clamp((1-p.y()/height())*255,0.,255.)};}
    void paintEvent(QPaintEvent*)override{QPainter p(this);p.fillRect(rect(),QColor("#17191e"));p.setPen(QColor("#343941"));for(int i=1;i<4;++i){p.drawLine(i*width()/4,0,i*width()/4,height());p.drawLine(0,i*height()/4,width(),i*height()/4);}if(!points)return;QPainterPath path;for(int x=0;x<width();++x){double y=height()*(1-effects_tools::curveValueUnchecked(*points,x*255./width())/255);if(x==0)path.moveTo(x,y);else path.lineTo(x,y);}p.setPen(QPen(QColor("#a8cfff"),2));p.drawPath(path);p.setBrush(QColor("#4e9aec"));for(auto value:*points)p.drawEllipse(QPointF(value.x/255*width(),(1-value.y/255)*height()),4,4);}
    void mousePressEvent(QMouseEvent* e)override{if(!points)return;const auto v=point(e->position());for(size_t i=0;i<points->size();++i)if(std::abs((*points)[i].x-v.x)<1){dragging=int(i);(*points)[i].y=v.y;if(changed)changed();update();return;}for(size_t i=0;i<points->size();++i)if(std::hypot((*points)[i].x-v.x,(*points)[i].y-v.y)<15){dragging=int(i);return;}if(points->size()>=32||v.x<=1||v.x>=254)return;auto at=std::lower_bound(points->begin(),points->end(),v.x,[](Point p,double x){return p.x<x;});dragging=int(at-points->begin());points->insert(at,v);if(changed)changed();update();}
    void mouseMoveEvent(QMouseEvent* e)override{if(!points||dragging<0)return;auto v=point(e->position());auto& current=(*points)[size_t(dragging)];if(dragging>0&&dragging+1<int(points->size())){const double lo=(*points)[size_t(dragging-1)].x,hi=(*points)[size_t(dragging+1)].x,pad=std::min(1.,(hi-lo)/3);current.x=std::clamp(v.x,lo+pad,hi-pad);}current.y=v.y;if(changed)changed();update();}
    void mouseReleaseEvent(QMouseEvent*)override{dragging=-1;}
    void mouseDoubleClickEvent(QMouseEvent* e)override{if(!points)return;auto p=point(e->position());for(size_t i=1;i+1<points->size();++i)if(std::hypot((*points)[i].x-p.x,(*points)[i].y-p.y)<15){points->erase(points->begin()+i);dragging=-1;if(changed)changed();update();return;}}
};
class GradeWheel final:public QWidget {
public:
    std::function<Point()> value;
    std::function<void(Point)> changed;
    GradeWheel(){setMinimumHeight(154);setMaximumHeight(180);setAccessibleName("Color grading wheel: drag for hue and saturation");setCursor(Qt::CrossCursor);}
protected:
    void paintEvent(QPaintEvent*)override{QPainter p(this);p.setRenderHint(QPainter::Antialiasing);const QPointF center(width()/2.,height()/2.);const double radius=std::min(width(),height())/2.-8;QConicalGradient hue(center,0);for(int i=0;i<=12;++i)hue.setColorAt(i/12.,QColor::fromHsvF(float(i%12/12.),1.f,.85f));p.setPen(Qt::NoPen);p.setBrush(hue);p.drawEllipse(center,radius,radius);QRadialGradient radial(center,radius);radial.setColorAt(0,QColor(220,220,220));radial.setColorAt(1,QColor(220,220,220,0));p.setBrush(radial);p.drawEllipse(center,radius,radius);if(value){auto v=value();const double angle=v.x*std::numbers::pi/180;QPointF selected=center+QPointF(std::cos(angle),-std::sin(angle))*(radius*v.y/100);p.setBrush(Qt::NoBrush);p.setPen(QPen(Qt::black,3));p.drawEllipse(selected,5,5);p.setPen(QPen(Qt::white,1));p.drawEllipse(selected,5,5);}}
    void assign(QPointF point){const double x=point.x()-width()/2.,y=height()/2.-point.y(),radius=std::min(width(),height())/2.-8;double hue=std::atan2(y,x)*180/std::numbers::pi;if(hue<0)hue+=360;if(changed)changed({hue,std::clamp(std::hypot(x,y)/radius*100,0.,100.)});update();}
    void mousePressEvent(QMouseEvent* e)override{if(e->button()==Qt::LeftButton)assign(e->position());}
    void mouseMoveEvent(QMouseEvent* e)override{if(e->buttons().testFlag(Qt::LeftButton))assign(e->position());}
    void mouseDoubleClickEvent(QMouseEvent*)override{if(changed)changed({0,0});update();}
};
class CameraSlider final:public ui::TrackSlider {
public:
    std::function<void()> reset;
    using TrackSlider::TrackSlider;
protected:
    void mouseDoubleClickEvent(QMouseEvent* event)override{if(event->button()==Qt::LeftButton&&reset){reset();event->accept();}else TrackSlider::mouseDoubleClickEvent(event);}
};
class ScrubLabel final:public QLabel {
    QPoint origin_;double start_{};bool dragging_{};
public:
    QDoubleSpinBox* field{};double initial{},sensitivity{1};using QLabel::QLabel;
protected:
    void mousePressEvent(QMouseEvent* e)override{if(e->button()==Qt::LeftButton&&field){origin_=e->globalPosition().toPoint();start_=field->value();dragging_=true;setCursor(Qt::SizeHorCursor);}}
    void mouseMoveEvent(QMouseEvent* e)override{if(dragging_&&field)field->setValue(start_+(e->globalPosition().x()-origin_.x())*sensitivity*(e->modifiers().testFlag(Qt::ShiftModifier)?.1:1));}
    void mouseReleaseEvent(QMouseEvent*)override{dragging_=false;unsetCursor();}
    void mouseDoubleClickEvent(QMouseEvent*)override{dragging_=false;if(field)field->setValue(initial);}
};
struct Output {std::shared_ptr<const Raster> raster;QString error;bool full{};};
class CameraPanel final:public ui::EditPanelSession {
    Document before_;Layer original_;std::shared_ptr<const Raster> previewSource_;
    effects::CameraRawSettings settings_,targetStart_;effects::CameraRawPreview view_;
    QDialog dialog_;ImageView* image_{};Scope* scope_{};QLabel* status_{};QPushButton* apply_{};QCheckBox* preview_{};QComboBox* picker_{};QComboBox* pointChoice_{};CurveView* curve_{};
    QList<QWidget*> draftControls_;std::map<std::string,QWidget*> controls_;std::map<std::string,bool> enabled_;std::vector<std::pair<double effects::CameraRawPointColor::*,QDoubleSpinBox*>> pointControls_;
    QTimer debounce_;QFutureWatcher<Output> worker_;std::shared_ptr<std::atomic_bool> token_=std::make_shared<std::atomic_bool>(false);uint64_t revision_{},running_{};bool pending_{},closed_{},committing_{},syncing_{};std::shared_ptr<const Raster> completed_;
    effects::CameraRawSettings effective()const{auto result=settings_;for(const auto& p:effects::cameraRawParameters())if(enabled_.contains(p.group)&&!enabled_.at(p.group))result.values[p.key]=p.initial;if(!enabled_.at("Curve"))for(auto& c:result.curves)c={{0,0},{255,255}};if(!enabled_.at("Mixer"))result.points.clear();if(!enabled_.at("Geometry"))result.guides.clear();return result;}
    void change(){if(closed_||committing_||syncing_)return;++revision_;apply_->setEnabled(false);debounce_.start();}
    void show(std::shared_ptr<const Raster> raster){if(!raster)return;image_->setImage(qimage(preview_->isChecked()?*raster:*previewSource_));scope_->setImage(image_->image());if(host_.preview){auto doc=before_;for(auto& l:doc.layers)if(l.id==original_.id){l.raster=raster;l.textJson.clear();l.shapeJson.clear();break;}host_.preview(preview_->isChecked()?std::make_shared<Document>(std::move(doc)):nullptr);}}
    void start(){if(closed_)return;if(worker_.isRunning()){pending_=true;token_->store(true);return;}if(host_.valid&&!host_.valid()){cancel();return;}pending_=false;running_=revision_;token_=std::make_shared<std::atomic_bool>(false);const auto token=token_;const bool full=committing_;const auto source=full?original_.raster:previewSource_;const auto settings=effective();const auto view=full?effects::CameraRawPreview{}:view_;const auto selection=before_.selection;const auto transform=original_.transform;const double scale=double(source->width)/original_.raster->width;status_->setText(full?"Applying Camera Raw…":"Updating preview…");worker_.setFuture(QtConcurrent::run([source,settings,view,full,token,selection,transform,scale]{Output out;out.full=full;try{out.raster=effects::applyCameraRaw(*source,settings,scale,view,[token]{return token->load();});if(selection){auto bytes=out.raster->rgba();for(int y=0;y<source->height;++y){if(token->load())throw std::runtime_error("Camera Raw cancelled");for(int x=0;x<source->width;++x){const auto p=transform.fromUnit({(x+.5)/source->width,(y+.5)/source->height});unsigned coverage=selection->coverage?selection->coverage->pixel(int(std::floor(p.x)),int(std::floor(p.y))):0;auto prior=source->pixel(x,y);const uint8_t channels[]{prior.r,prior.g,prior.b,prior.a};for(int c=0;c<4;++c){auto& b=bytes[(size_t(y)*source->width+x)*4+c];b=uint8_t((b*coverage+channels[c]*(255-coverage)+127)/255);}}}out.raster=Raster::fromRgba(source->width,source->height,bytes.data(),size_t(source->width)*4);}if(full&&out.raster->width==source->width&&out.raster->height==source->height&&std::equal(out.raster->tiles.begin(),out.raster->tiles.end(),source->tiles.begin(),source->tiles.end(),[](const auto& a,const auto& b){return a==b||a->pixels==b->pixels;}))out.raster=source;}catch(const std::exception& e){out.error=QString::fromUtf8(e.what());}return out;}));}
    void finish(bool apply){if(closed_)return;closed_=true;token_->store(true);debounce_.stop();dialog_.hide();if(apply&&completed_)try{auto raster=completed_;auto merge=[raster,original=original_.raster](const Layer& current){auto result=current;result.raster=raster;if(raster!=original){result.textJson.clear();result.shapeJson.clear();}return result;};auto doc=before_;for(auto& l:doc.layers)if(l.id==original_.id){l=merge(l);break;}if(host_.commit)host_.commit({std::move(doc),original_.id,false,merge});QSettings().setValue("filters/cameraRaw",QString::fromStdString(effects::encodeCameraRawSettings(settings_)));}catch(const std::exception& e){if(host_.error)host_.error(QString::fromUtf8(e.what()));}if(host_.preview)host_.preview(nullptr);if(host_.closed)host_.closed();host_={};if(!worker_.isRunning())deleteLater();}
    void synchronize(){syncing_=true;for(const auto& [key,widget]:controls_){const double value=settings_.get(key);if(auto* n=qobject_cast<QDoubleSpinBox*>(widget))n->setValue(value);else if(auto* c=qobject_cast<QCheckBox*>(widget))c->setChecked(value!=0);else if(auto* combo=qobject_cast<QComboBox*>(widget))combo->setCurrentIndex(int(value)-(key=="process"?1:0));}syncing_=false;if(curve_)curve_->update();}
    void pointSync(){syncing_=true;const auto index=pointChoice_->currentIndex();for(const auto& [member,spin]:pointControls_){spin->setEnabled(index>=0);spin->setValue(index>=0?settings_.points[size_t(index)].*member:0);}syncing_=false;}
    void sample(Point p){if(picker_->currentIndex()==1){auto wb=effects::cameraRawWhiteBalance(*previewSource_,Point{p.x*previewSource_->width,p.y*previewSource_->height});if(wb){settings_.set("temperature",wb->x);settings_.set("tint",wb->y);synchronize();change();}}else if(picker_->currentIndex()==2&&settings_.points.size()<32){auto pixel=previewSource_->pixel(int(p.x*previewSource_->width),int(p.y*previewSource_->height));if(!pixel.a)return;QColor color=QColor::fromRgbF(pixel.r/double(pixel.a),pixel.g/double(pixel.a),pixel.b/double(pixel.a));effects::CameraRawPointColor point;point.hue=std::max(0.,double(color.hslHueF()))*360;point.saturation=color.hslSaturationF();point.luminance=color.lightnessF();settings_.points.push_back(point);pointChoice_->addItem(QString("Point %1").arg(settings_.points.size()));pointChoice_->setCurrentIndex(int(settings_.points.size())-1);change();}}
public:
    CameraPanel(QWidget* parent,const Document& document,const Layer& layer,ui::EditPanelHost host):EditPanelSession(parent,Kind::Filter,false,std::move(host)),before_(document),original_(layer),dialog_(parent){
        try{auto stored=QSettings().value("filters/cameraRaw").toString();if(!stored.isEmpty())settings_=effects::decodeCameraRawSettings(stored.toStdString());}catch(const std::exception&){}
        previewSource_=original_.raster;while(std::max(previewSource_->width,previewSource_->height)>1000)previewSource_=graphics::DownsampleCache::halve(*previewSource_);
        dialog_.setObjectName("cameraRawWorkspace");dialog_.setWindowTitle("Camera Raw");dialog_.resize(1120,790);dialog_.setMinimumSize(780,580);auto* root=new QVBoxLayout(&dialog_);auto* body=new QHBoxLayout;root->addLayout(body,1);auto* imageColumn=new QVBoxLayout;image_=new ImageView;imageColumn->addWidget(image_,1);body->addLayout(imageColumn,1);
        auto* sampleBar=new QHBoxLayout;picker_=new QComboBox;picker_->addItems({"Inspect / zoom","White balance eyedropper","Point color eyedropper","Upright guides","Targeted tone adjustment","Targeted color adjustment"});sampleBar->addWidget(picker_);auto* autoWb=new QPushButton("Auto White Balance");sampleBar->addWidget(autoWb);imageColumn->addLayout(sampleBar);connect(autoWb,&QPushButton::clicked,this,[this]{if(auto wb=effects::cameraRawWhiteBalance(*previewSource_)){settings_.set("temperature",wb->x);settings_.set("tint",wb->y);synchronize();change();}});connect(picker_,&QComboBox::currentIndexChanged,this,[this](int i){image_->drawGuides=i==3;image_->targeting=i==4||i==5;});image_->sampled=[this](Point p){sample(p);};image_->targeted=[this](Point p,double delta,Qt::KeyboardModifiers modifiers,bool begin){if(begin){targetStart_=settings_;return;}auto pixel=previewSource_->pixel(int(p.x*previewSource_->width),int(p.y*previewSource_->height));if(!pixel.a)return;QColor color=QColor::fromRgbF(pixel.r/double(pixel.a),pixel.g/double(pixel.a),pixel.b/double(pixel.a));if(picker_->currentIndex()==4){double tone=color.lightnessF();const char* key=tone<settings_.get("shadowSplit")/100?"curveShadows":tone<settings_.get("darkSplit")/100?"curveDarks":tone<settings_.get("lightSplit")/100?"curveLights":"curveHighlights";settings_.set(key,std::clamp(targetStart_.get(key)+delta*.5,-100.,100.));}else{const char* channel=modifiers.testFlag(Qt::ControlModifier)?"Hue":modifiers.testFlag(Qt::ShiftModifier)?"Luminance":"Saturation";const char* families[]{"red","orange","yellow","green","aqua","blue","purple","magenta"};const double centers[]{0,30,60,120,180,240,270,300};double hue=std::max(0.,double(color.hslHueF()))*360;for(size_t i=0;i<8;++i){double distance=std::abs(hue-centers[i]);if(distance>180)distance=360-distance;double weight=std::max(0.,1-distance/40);std::string key=std::string(families[i])+channel;settings_.set(key,std::clamp(targetStart_.get(key)+delta*.5*weight,-100.,100.));}}synchronize();change();};image_->guided=[this](Point a,Point b){if(std::hypot(a.x-b.x,a.y-b.y)<.01)return;if(settings_.guides.size()==4)settings_.guides.erase(settings_.guides.begin());settings_.guides.push_back({a,b});settings_.set("upright",1);image_->guides=settings_.guides;image_->update();synchronize();change();};
        auto* controls=new QWidget;controls->setMinimumWidth(330);controls->setMaximumWidth(440);auto* right=new QVBoxLayout(controls);scope_=new Scope;right->addWidget(scope_);auto* scopeMode=new QComboBox;scopeMode->addItems({"RGB histogram","Vectorscope"});right->addWidget(scopeMode);connect(scopeMode,&QComboBox::currentIndexChanged,this,[this](int index){scope_->setVector(index==1);});auto* tabs=new QTabWidget;tabs->setObjectName("cameraRawSections");tabs->setUsesScrollButtons(true);right->addWidget(tabs,1);body->addWidget(controls);
        std::map<std::string,QFormLayout*> forms;for(const char* group:{"Light","Color","Effects","Curve","Mixer","Grading","Detail","Optics","Geometry","Calibration"}){enabled_[group]=true;auto* scroll=new QScrollArea;scroll->setWidgetResizable(true);auto* page=new QWidget;auto* form=new QFormLayout(page);form->setFieldGrowthPolicy(QFormLayout::AllNonFixedFieldsGrow);auto* enabled=new QCheckBox(QString("Enable %1").arg(group));enabled->setChecked(true);form->addRow(enabled);connect(enabled,&QCheckBox::toggled,this,[this,name=std::string(group)](bool value){enabled_[name]=value;change();});scroll->setWidget(page);tabs->addTab(scroll,group);forms[group]=form;}
        for(const auto& parameter:effects::cameraRawParameters()){
            const std::string key=parameter.key;auto* form=forms[parameter.group];if(parameter.maximum==1&&parameter.minimum==0){auto* check=new QCheckBox(parameter.label);check->setObjectName(QString::fromStdString("cameraRaw_"+key));check->setChecked(settings_.get(key)!=0);form->addRow(check);controls_[key]=check;connect(check,&QCheckBox::toggled,this,[this,key](bool value){settings_.set(key,value?1:0);change();});continue;}
            if(key=="glowStyle"||key=="vignetteStyle"||key=="process"){auto* combo=new QComboBox;combo->setObjectName(QString::fromStdString("cameraRaw_"+key));if(key=="glowStyle")combo->addItems({"Diffusion","Bloom","Halation"});else if(key=="vignetteStyle")combo->addItems({"Highlight Priority","Color Priority","Paint Overlay"});else combo->addItems({"Version 1","Version 2","Version 3","Version 4","Version 5","Version 6"});combo->setCurrentIndex(int(settings_.get(key))-(key=="process"?1:0));form->addRow(parameter.label,combo);controls_[key]=combo;connect(combo,&QComboBox::currentIndexChanged,this,[this,key](int index){settings_.set(key,index+(key=="process"?1:0));change();});continue;}
            auto* row=new QWidget;auto* h=new QHBoxLayout(row);h->setContentsMargins(0,0,0,0);auto* slider=new CameraSlider(Qt::Horizontal);const int factor=key=="exposure"?100:1;slider->setRange(int(parameter.minimum*factor),int(parameter.maximum*factor));slider->setValue(int(settings_.get(key)*factor));auto* number=new ui::PropertyNumber;number->setRange(parameter.minimum,parameter.maximum);number->setDecimals(factor==100?2:1);number->setValue(settings_.get(key));number->setMaximumWidth(82);number->setAccessibleName(parameter.label);number->setObjectName(QString::fromStdString("cameraRaw_"+key));h->addWidget(slider,1);h->addWidget(number);auto* label=new ScrubLabel(parameter.label);label->field=number;label->initial=parameter.initial;label->sensitivity=factor==100?.01:1;label->setToolTip("Drag to adjust; double-click to reset");slider->reset=[number,initial=parameter.initial]{number->setValue(initial);};form->addRow(label,row);controls_[key]=number;connect(slider,&QSlider::valueChanged,this,[number,factor](int v){number->setValue(double(v)/factor);});connect(number,&QDoubleSpinBox::valueChanged,this,[this,key,slider,factor](double v){const QSignalBlocker block(slider);slider->setValue(int(std::round(v*factor)));settings_.set(key,v);change();});connect(slider,&QSlider::sliderPressed,this,[this,key]{if(QApplication::keyboardModifiers().testFlag(Qt::AltModifier)){if(key=="shadows"||key=="blacks")view_.clipping=2;else if(key=="exposure"||key=="highlights"||key=="whites")view_.clipping=1;else if(key=="sharpenMasking")view_.sharpenMask=true;change();}});connect(slider,&QSlider::sliderReleased,this,[this]{view_.clipping=0;view_.sharpenMask=false;change();});
        }
        auto* wheelPage=new QWidget;auto* wheelGrid=new QGridLayout(wheelPage);wheelGrid->setContentsMargins(0,0,0,0);int wheelIndex=0;forms["Grading"]->insertRow(1,wheelPage);for(const auto* wheelName:{"Shadow","Midtone","Highlight","Global"}){auto* wheelCell=new QWidget;auto* wheelLayout=new QVBoxLayout(wheelCell);wheelLayout->setContentsMargins(0,0,0,0);auto* wheelLabel=new QLabel(wheelName);wheelLabel->setAlignment(Qt::AlignCenter);wheelLayout->addWidget(wheelLabel);auto* wheel=new GradeWheel;wheel->setMinimumHeight(125);wheel->setMaximumHeight(145);wheelLayout->addWidget(wheel);wheelGrid->addWidget(wheelCell,wheelIndex/2,wheelIndex%2);++wheelIndex;const std::string base=std::string("grade")+wheelName;wheel->value=[this,base]{return Point{settings_.get(base+"Hue"),settings_.get(base+"Saturation")};};wheel->changed=[this,base](Point value){settings_.set(base+"Hue",value.x);settings_.set(base+"Saturation",value.y);synchronize();change();};for(const auto& key:{base+"Hue",base+"Saturation"})if(auto* spin=qobject_cast<QDoubleSpinBox*>(controls_[key]))connect(spin,&QDoubleSpinBox::valueChanged,wheel,[wheel]{wheel->update();});}
        auto* curveChannel=new QComboBox;curveChannel->addItems({"RGB point curve","Red point curve","Green point curve","Blue point curve"});forms["Curve"]->addRow(curveChannel);curve_=new CurveView;curve_->points=&settings_.curves[0];curve_->changed=[this]{change();};forms["Curve"]->addRow(curve_);connect(curveChannel,&QComboBox::currentIndexChanged,this,[this](int index){curve_->points=&settings_.curves[size_t(index)];curve_->update();});auto* preset=new QComboBox;preset->addItems({"Linear","Medium contrast","Strong contrast"});forms["Curve"]->addRow("Curve preset",preset);connect(preset,&QComboBox::activated,this,[this](int index){*curve_->points=index==0?std::vector<Point>{{0,0},{255,255}}:std::vector<Point>{{0,0},{63.75,index==1?45.9:25.5},{191.25,index==1?209.1:229.5},{255,255}};curve_->update();change();});
        pointChoice_=new QComboBox;forms["Mixer"]->addRow("Point color",pointChoice_);for(size_t i=0;i<settings_.points.size();++i)pointChoice_->addItem(QString("Point %1").arg(i+1));connect(pointChoice_,&QComboBox::currentIndexChanged,this,[this]{pointSync();if(view_.pointColor>=0){view_.pointColor=pointChoice_->currentIndex();change();}});auto addPoint=[&](const char* label,double effects::CameraRawPointColor::* member,double lo,double hi){auto* spin=new ui::PropertyNumber;spin->setRange(lo,hi);spin->setDecimals(hi<=1?2:1);forms["Mixer"]->addRow(label,spin);pointControls_.push_back({member,spin});connect(spin,&QDoubleSpinBox::valueChanged,this,[this,member](double value){if(syncing_||pointChoice_->currentIndex()<0)return;settings_.points[size_t(pointChoice_->currentIndex())].*member=value;change();});};addPoint("Point hue shift",&effects::CameraRawPointColor::hueShift,-100,100);addPoint("Point saturation shift",&effects::CameraRawPointColor::saturationShift,-100,100);addPoint("Point luminance shift",&effects::CameraRawPointColor::luminanceShift,-100,100);addPoint("Hue range",&effects::CameraRawPointColor::hueRange,1,180);addPoint("Saturation range",&effects::CameraRawPointColor::saturationRange,.01,1);addPoint("Luminance range",&effects::CameraRawPointColor::luminanceRange,.01,1);auto* visualize=new QCheckBox("Visualize point color range");forms["Mixer"]->addRow(visualize);connect(visualize,&QCheckBox::toggled,this,[this](bool value){view_.pointColor=value?pointChoice_->currentIndex():-1;change();});auto* removePoint=new QPushButton("Remove Point Color");forms["Mixer"]->addRow(removePoint);connect(removePoint,&QPushButton::clicked,this,[this]{auto index=pointChoice_->currentIndex();if(index<0)return;settings_.points.erase(settings_.points.begin()+index);pointChoice_->removeItem(index);view_.pointColor=-1;pointSync();change();});pointSync();auto* clearGuides=new QPushButton("Clear Upright Guides");forms["Geometry"]->addRow(clearGuides);connect(clearGuides,&QPushButton::clicked,this,[this]{settings_.guides.clear();image_->guides.clear();image_->update();change();});
        auto* opticsNote=new QLabel("Lens correction uses generic strength on rendered layers.");opticsNote->setWordWrap(true);forms["Optics"]->addRow(opticsNote);auto* footer=new QHBoxLayout;preview_=new QCheckBox("Preview");preview_->setChecked(true);footer->addWidget(preview_);connect(preview_,&QCheckBox::toggled,this,[this](bool checked){if(checked)show(completed_?completed_:previewSource_);else{image_->setImage(qimage(*previewSource_));if(host_.preview)host_.preview(nullptr);}});auto* shadows=new QCheckBox("Shadow clipping");auto* highlights=new QCheckBox("Highlight clipping");footer->addWidget(shadows);footer->addWidget(highlights);connect(shadows,&QCheckBox::toggled,this,[this](bool v){view_.shadowOverlay=v;change();});connect(highlights,&QCheckBox::toggled,this,[this](bool v){view_.highlightOverlay=v;change();});auto* reset=new QPushButton("Reset");footer->addWidget(reset);connect(reset,&QPushButton::clicked,this,[this]{settings_=effects::CameraRawSettings{};synchronize();pointChoice_->clear();pointSync();image_->guides.clear();change();});root->addLayout(footer);status_=new QLabel;status_->setWordWrap(true);root->addWidget(status_);auto* buttons=new QDialogButtonBox(QDialogButtonBox::Apply|QDialogButtonBox::Cancel);apply_=buttons->button(QDialogButtonBox::Apply);root->addWidget(buttons);connect(buttons->button(QDialogButtonBox::Cancel),&QPushButton::clicked,this,[this]{finish(false);});connect(&dialog_,&QDialog::rejected,this,[this]{finish(false);});draftControls_={controls,image_,picker_,autoWb,preview_,shadows,highlights,reset};connect(apply_,&QPushButton::clicked,this,[this]{if(committing_)return;committing_=true;for(auto* control:draftControls_)control->setEnabled(false);apply_->setEnabled(false);if(host_.stateChanged)host_.stateChanged();++revision_;debounce_.stop();start();});
        debounce_.setSingleShot(true);debounce_.setInterval(90);connect(&debounce_,&QTimer::timeout,this,[this]{start();});connect(&worker_,&QFutureWatcher<Output>::finished,this,[this]{if(closed_){deleteLater();return;}auto out=worker_.result();if(pending_||running_!=revision_){start();return;}if(!out.error.isEmpty()){committing_=false;for(auto* control:draftControls_)control->setEnabled(true);status_->setText(out.error);apply_->setEnabled(false);if(host_.stateChanged)host_.stateChanged();return;}completed_=out.raster;if(out.full){finish(true);return;}status_->setText("Ready · Alt-drag Light sliders to inspect clipping · wheel to zoom");apply_->setEnabled(true);show(completed_);});image_->setImage(qimage(*previewSource_));dialog_.show();change();
    }
    ~CameraPanel()override{token_->store(true);worker_.waitForFinished();}
    QDialog* panel()const override{return const_cast<QDialog*>(&dialog_);}bool committing()const override{return committing_;}void cancel()override{finish(false);}
};
}
ui::EditPanelSession* openCameraRawPanel(QWidget* parent,const Document& doc,const Layer& layer,ui::EditPanelHost host){if(!layer.raster||layer.group||!layer.adjustmentJson.empty())throw std::runtime_error("Camera Raw requires an image layer");return new CameraPanel(parent,doc,layer,std::move(host));}
}
