#include "editing/Text.h"
#include "editing/DocumentGeometry.h"
#include "editing/PixelEdits.h"
#include "editing_transform/Distortion.h"
#include "editing_transform/PixelTransform.h"
#include "graphics/GrowingBrushSession.h"
#include "layers/LayerOperations.h"
#include "persistence/ProjectStore.h"
#include "ui/MainWindow.h"
#include "ui/LayerClipboard.h"
#include <QApplication>
#include <QClipboard>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QElapsedTimer>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMimeData>
#include <QPlainTextEdit>
#include <QPushButton>
#include <QTemporaryDir>
#include <QTest>
#include <filesystem>
#include <cmath>
#include <iostream>
#include <map>
#include <stdexcept>

using namespace compositor;
#define REQUIRE(...) do{if(!(__VA_ARGS__))throw std::runtime_error(std::string("line ")+std::to_string(__LINE__)+": " #__VA_ARGS__);}while(false)
namespace {
editing::TextStyle sample(){editing::TextStyle style;style.content=QString::fromUtf8("Windows — café 🙂\nSecond line");style.fontSize=30;style.red=.2;style.green=.6;style.blue=.9;return style;}
Document fixture(){Document d;d.id=newId();d.width=640;d.height=420;auto l=editing::createTextLayer({20,30},sample());d.layers={l};return d;}
struct Bounds {int left{30000},top{30000},right{},bottom{};};
Bounds ink(const Raster& r){Bounds b;for(int y=0;y<r.height;++y)for(int x=0;x<r.width;++x){auto p=r.pixel(x,y);REQUIRE(p.r<=p.a&&p.g<=p.a&&p.b<=p.a);if(p.a){b.left=std::min(b.left,x);b.top=std::min(b.top,y);b.right=std::max(b.right,x+1);b.bottom=std::max(b.bottom,y+1);}}return b;}
void metadata(){auto s=sample();s.tracking=2.25;s.leading=46;s.alignment=editing::TextAlignment::Center;s.boxSize=QSizeF(350,160);REQUIRE(editing::decodeTextStyle(editing::encodeTextStyle(s))==s);s.content=QString(99998,QChar('a'))+QString::fromUtf8("🙂");REQUIRE(s.valid());s.content+='x';REQUIRE(!s.valid());s=sample();s.boxSize=QSizeF(16,30001);REQUIRE(!s.valid());auto json=QJsonDocument::fromJson(QByteArray::fromStdString(editing::encodeTextStyle(sample()))).object();json["alignment"]="Justified";bool rejected=false;try{editing::decodeTextStyle(QJsonDocument(json).toJson().toStdString());}catch(...){rejected=true;}REQUIRE(rejected);auto fallback=sample();fallback.fontName.clear();REQUIRE(fallback.valid()&&editing::decodeTextStyle(editing::encodeTextStyle(fallback))==fallback&&editing::textRaster(fallback));fallback.fontName=QString(300,QChar('x'))+"\nunknown";REQUIRE(fallback.valid()&&editing::decodeTextStyle(editing::encodeTextStyle(fallback))==fallback&&editing::textRaster(fallback));}
void layout(){auto s=sample();auto raster=editing::textRaster(s);auto initial=ink(*raster);REQUIRE(initial.right>initial.left&&initial.bottom>initial.top);auto tracked=s;tracked.tracking=5;REQUIRE(editing::textBoxSize(tracked).width()>raster->width);auto spaced=s;spaced.leading=80;REQUIRE(editing::textBoxSize(spaced).height()>raster->height);s.content="A";s.boxSize=QSizeF(240,90);s.alignment=editing::TextAlignment::Left;auto left=ink(*editing::textRaster(s));s.alignment=editing::TextAlignment::Right;auto right=ink(*editing::textRaster(s));REQUIRE(right.left>left.left+100);s.content="one two three four five six";s.boxSize=QSizeF(110,230);auto wrapped=ink(*editing::textRaster(s));REQUIRE(wrapped.bottom>90);REQUIRE(wrapped.left>=12&&wrapped.right<=98&&wrapped.bottom<=218);}
void transform(){auto d=fixture();auto source=d.layers[0];source.transform={100,80,source.transform.width*1.4,source.transform.height*.8,37,true,false};source.mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{128}})};source.effectsJson="[]";source.maskSourceId="reference";auto s=editing::decodeTextStyle(source.textJson);s.content+=" a longer paragraph";auto changed=editing::restyleText(source,s);auto before=source.transform.fromUnit({0,0}),after=changed.transform.fromUnit({0,0});REQUIRE(std::hypot(before.x-after.x,before.y-after.y)<1e-8);REQUIRE(changed.transform.rotation==37&&changed.transform.flipX&&changed.mask->placement==source.transform);REQUIRE(changed.effectsJson==source.effectsJson&&changed.maskSourceId==source.maskSourceId);REQUIRE(changed.raster!=source.raster&&source.textJson!=changed.textJson);}
void operations(){auto d=fixture();auto original=d.layers[0];auto duplicate=layers::duplicateLayer(d,{{original.id},original.id},original.id);REQUIRE(duplicate.document.layers.size()==2);REQUIRE(duplicate.document.layers[1].textJson==original.textJson&&duplicate.document.layers[1].raster==original.raster);auto cropped=editing::cropDocument(d,{10,10,400,300});REQUIRE(cropped.layers[0].textJson==original.textJson);auto flipped=editing::flipCanvas(d,true);REQUIRE(flipped.layers[0].textJson==original.textJson);d.selection=editing::rasterSelection(editing::SelectionOutline::rectangle({0,0,640,420},false),640,420);auto erased=editing::editLayer(original,d,editing::PixelEdit::Clear,{});REQUIRE(erased.textJson.empty());d.layers[0].mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{128}})};auto masked=editing::editLayer(d.layers[0],d,editing::PixelEdit::Fill,{255,255,255,255},true);REQUIRE(masked.textJson==original.textJson);auto resized=editing::imageResize(d,{320,210,72,Transform::Sampling::High});REQUIRE(resized.layers[0].textJson.empty());}
void roundtrip(){QTemporaryDir temp;REQUIRE(temp.isValid());auto path=std::filesystem::path(temp.path().toStdWString())/L"Unicode 文本.comp";ProjectStore store(makeWicProjectCodec());auto d=fixture();store.save(path,d,d.layers[0].id);auto loaded=store.load(path);REQUIRE(loaded.readVersion==9&&loaded.document.layers[0].textJson==d.layers[0].textJson);REQUIRE(loaded.document.layers[0].raster->rgba()==d.layers[0].raster->rgba());auto style=editing::decodeTextStyle(loaded.document.layers[0].textJson);style.content+=" reopened";loaded.document.layers[0]=editing::restyleText(loaded.document.layers[0],style);store.save(path,loaded.document,loaded.activeLayer);auto reopened=store.load(path);REQUIRE(editing::decodeTextStyle(reopened.document.layers[0].textJson).content==style.content);REQUIRE(SoftwareRenderer().render(reopened.document,0,0,640,420)->rgba()==SoftwareRenderer().render(loaded.document,0,0,640,420)->rgba());}
QAction* command(MainWindow& window,const QString& text){for(auto* action:window.findChildren<QAction*>())if(action->text()==text)return action;throw std::runtime_error("Missing text command");}
void finishPaste(MainWindow& window){QElapsedTimer timer;timer.start();while(window.findChild<QObject*>("projectLayerCopyJob")){REQUIRE(timer.elapsed()<10000);QTest::qWait(5);}}
void lifecycle(){MainWindow window(true);auto d=fixture();auto& p=window.addProject(d);command(window,"Edit Text Layer…")->trigger();auto* panel=window.findChild<QDialog*>("textEditorPanel");REQUIRE(panel);auto* input=panel->findChild<QPlainTextEdit*>("textContent");REQUIRE(input);input->appendPlainText("cancel me");QTest::qWait(100);REQUIRE(p.textPreview&&p.document==d&&p.history.undoCount()==0);panel->reject();QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);REQUIRE(!p.textPreview&&p.document==d);command(window,"Edit Text Layer…")->trigger();panel=window.findChild<QDialog*>("textEditorPanel");input=panel->findChild<QPlainTextEdit*>("textContent");input->appendPlainText("committed");input->undo();REQUIRE(input->toPlainText()==sample().content);input->redo();panel->findChild<QPushButton*>("textApply")->click();QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);REQUIRE(p.history.undoCount()==1&&!p.textPreview);REQUIRE(editing::decodeTextStyle(p.document->layers[0].textJson).content.endsWith("committed"));auto prior=p.history.undo();REQUIRE(prior&&prior->document==d);}
void creation(){MainWindow window(true);Document d;d.id=newId();auto& p=window.addProject(d);command(window,"Type (T)")->trigger();p.canvas->pointerDown({30,40},{});p.canvas->pointerMove({330,200},{});p.canvas->pointerUp({330,200},{});auto* panel=window.findChild<QDialog*>("textEditorPanel");REQUIRE(panel);panel->findChild<QPlainTextEdit*>("textContent")->setPlainText("Paragraph box");panel->findChild<QPushButton*>("textApply")->click();QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);REQUIRE(p.history.undoCount()==1&&p.document->layers.size()==1);const auto& layer=p.document->layers[0];REQUIRE(layer.transform==Transform{30,40,300,160});REQUIRE(editing::decodeTextStyle(layer.textJson).boxSize==QSizeF(300,160));}
void clippedTransfer(){auto d=fixture();Layer base;base.id=newId();base.raster=Raster::filled(130,420,{0,0,0,255});base.transform={0,0,130,420};base.visible=false;d.layers[0].maskSourceId=base.id;d.layers.insert(d.layers.begin(),base);Document target;target.id=newId();target.width=d.width;target.height=d.height;const auto source=d.layers.back();const auto copied=layers::copySubtree(d,source.id,target,source.transform.fromUnit({.5,.5}));const auto& text=copied.edit.document.layers.back();REQUIRE(text.textJson==source.textJson&&text.raster==source.raster&&text.mask&&text.mask->placement&&text.maskSourceId.empty());const auto before=SoftwareRenderer().render(d,0,0,640,420),after=SoftwareRenderer().render(copied.edit.document,0,0,640,420);for(int y=0;y<420;++y)for(int x=0;x<640;++x){const auto a=before->pixel(x,y),b=after->pixel(x,y);REQUIRE(std::abs(int(a.a)-b.a)<=2);}const auto erased=layers::erase(d,{{base.id},base.id},layers::DeleteMode::Bake);REQUIRE(erased.document.layers.size()==1&&erased.document.layers[0].textJson==source.textJson);}
void lines(){editing::ShapeStyle s;s.kind=editing::ShapeKind::Line;s.lineWidth=8;s.red=1;auto made=editing::createLineLayer({100,20},{20,100},s,"Line");REQUIRE(made);auto decoded=editing::decodeShapeStyle(made->shapeJson);REQUIRE(decoded.kind==editing::ShapeKind::Line&&decoded.start&&decoded.end&&decoded.start->x>decoded.end->x&&decoded.start->y<decoded.end->y);REQUIRE(editing::decodeShapeStyle(editing::encodeShapeStyle(decoded))==decoded);auto start=made->transform.fromUnit(*decoded.start),end=made->transform.fromUnit(*decoded.end);REQUIRE(std::hypot(start.x-100,start.y-20)<1e-8&&std::hypot(end.x-20,end.y-100)<1e-8);auto raster=made->raster;REQUIRE(raster->pixel(raster->width/2,raster->height/2).a>200&&raster->pixel(1,1).a==0);auto flat=editing::createLineLayer({10,20},{150,20},s,"Horizontal");REQUIRE(flat&&flat->raster->height==8);auto snapped=editing::snappedLineEnd({0,0},{40,31},true);REQUIRE(std::abs(snapped.x-snapped.y)<1e-8);REQUIRE(!editing::createLineLayer({0,0},{0,0},s,"No drag"));auto enlarged=*made;enlarged.transform.width*=2;enlarged=editing::redrawShape(enlarged);REQUIRE(enlarged.raster->width==made->raster->width*2&&editing::decodeShapeStyle(enlarged.shapeJson)==decoded);}
void lineCreation(){MainWindow window(true);Document d;d.id=newId();auto& p=window.addProject(d);command(window,"Shape (U)")->trigger();auto* kind=window.findChild<QComboBox*>("shapeKind");REQUIRE(kind&&kind->count()==3);kind->setCurrentIndex(2);window.findChild<QDoubleSpinBox*>("shapeLineWidth")->setValue(10);p.canvas->pointerDown({100,50},{});p.canvas->pointerMove({30,150},{});p.canvas->pointerUp({30,150},{});REQUIRE(p.document->layers.size()==1&&p.history.undoName()=="Line");const auto style=editing::decodeShapeStyle(p.document->layers[0].shapeJson);REQUIRE(style.kind==editing::ShapeKind::Line&&style.lineWidth==10&&style.start->x>style.end->x);}
void duplicateGroup(){auto d=fixture();Layer folder;folder.id=newId();folder.name="Folder";folder.group=true;folder.transform={0,0,640,420};d.layers[0].parentId=folder.id;d.layers.insert(d.layers.begin(),folder);auto second=d.layers.back();second.id=newId();second.parentId.clear();second.transform.x+=180;d.layers.push_back(second);const auto copied=layers::duplicateLayers(d,{{folder.id,d.layers[1].id,second.id},folder.id});REQUIRE(copied.document.layers.size()==6&&copied.selection.ids.size()==2&&copied.copiedIds.size()==3);const auto childId=copied.copiedIds.at(d.layers[1].id);const auto child=std::find_if(copied.document.layers.begin(),copied.document.layers.end(),[&](const Layer& l){return l.id==childId;});REQUIRE(child!=copied.document.layers.end()&&child->parentId==copied.copiedIds.at(folder.id)&&child->textJson==d.layers[1].textJson&&child->raster==d.layers[1].raster);Document target;target.id=newId();target.width=640;target.height=420;const auto transfer=layers::copyLayers(d,{folder.id,second.id},target);REQUIRE(transfer.edit.selection.ids.size()==2&&transfer.edit.document.layers.size()==3);const auto& firstText=transfer.edit.document.layers[1];const auto& secondText=transfer.edit.document.layers[2];REQUIRE(std::abs((secondText.transform.x-firstText.transform.x)-180)<1e-8);}
void clipboardLayers(){MainWindow window(true);auto d=fixture();Layer folder;folder.id=newId();folder.name="Folder";folder.group=true;folder.transform={0,0,640,420};d.layers[0].parentId=folder.id;d.layers.insert(d.layers.begin(),folder);auto& project=window.addProject(d);project.active=folder.id;project.selected={folder.id};command(window,"Type (T)")->trigger();command(window,"Copy")->trigger();REQUIRE(QApplication::clipboard()->mimeData()->hasFormat(ui::copiedLayerMime));command(window,"Paste")->trigger();finishPaste(window);REQUIRE(project.document->layers.size()==4&&project.history.undoName()=="Paste");const auto copied=std::find_if(project.document->layers.begin(),project.document->layers.end(),[&](const Layer& l){return l.id==project.active;});REQUIRE(copied!=project.document->layers.end()&&copied->group);REQUIRE(std::count_if(project.document->layers.begin(),project.document->layers.end(),[](const Layer& l){return !l.textJson.empty();})==2);QApplication::clipboard()->setText("plain text replacement");const auto count=project.document->layers.size();command(window,"Paste")->trigger();REQUIRE(project.document->layers.size()==count);}
Document clipboardFixture(){auto d=fixture();d.layers[0].effectsJson=R"({"colorOverlay":{"red":0.8,"green":0.2,"blue":0.1,"opacity":0.7,"enabled":true}})";d.layers[0].mask=Mask{std::make_shared<GrayRaster>(GrayRaster{1,1,{220}})};return d;}
const Layer& activeLayer(const EditorProject& project){auto found=std::find_if(project.document->layers.begin(),project.document->layers.end(),[&](const Layer& layer){return layer.id==project.active;});REQUIRE(found!=project.document->layers.end());return *found;}
void clipboardSnapshotEdit(){MainWindow window(true);auto d=clipboardFixture();const auto captured=d.layers[0];auto& project=window.addProject(d);command(window,"Copy")->trigger();command(window,"Edit Text Layer…")->trigger();auto* panel=window.findChild<QDialog*>("textEditorPanel");REQUIRE(panel);panel->findChild<QPlainTextEdit*>("textContent")->setPlainText("Changed after Copy");panel->findChild<QPushButton*>("textApply")->click();QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);project.document->layers[0].effectsJson.clear();project.document->layers[0].transform.x+=35;const auto edited=*project.document;command(window,"Paste")->trigger();finishPaste(window);const auto& pasted=activeLayer(project);REQUIRE(pasted.textJson==captured.textJson&&pasted.effectsJson==captured.effectsJson&&pasted.raster==captured.raster&&pasted.mask==captured.mask&&pasted.transform==captured.transform);REQUIRE(project.document->layers[0]==edited.layers[0]);auto undo=project.history.undo();REQUIRE(undo&&undo->document==edited);}
void clipboardSnapshotDelete(){MainWindow window(true);auto d=clipboardFixture();const auto captured=d.layers[0];Layer folder;folder.id=newId();folder.name="Copied Folder";folder.group=true;folder.transform={0,0,640,420};d.layers[0].parentId=folder.id;d.layers.insert(d.layers.begin(),folder);auto& project=window.addProject(d);project.active=folder.id;project.selected={folder.id};command(window,"Move (V)")->trigger();command(window,"Copy")->trigger();command(window,"Delete Layer")->trigger();REQUIRE(project.document->layers.empty());command(window,"Paste")->trigger();finishPaste(window);REQUIRE(project.document->layers.size()==2&&activeLayer(project).group);const auto& child=project.document->layers[1];REQUIRE(child.parentId==project.active&&child.textJson==captured.textJson&&child.effectsJson==captured.effectsJson&&child.raster==captured.raster&&child.mask==captured.mask);}
void clipboardSnapshotClose(){MainWindow window(true);auto d=clipboardFixture();const auto captured=d.layers[0];window.addProject(d);QPointer<NativeCanvas> origin=window.canvas();command(window,"Copy")->trigger();command(window,"Close Project")->trigger();QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);REQUIRE(origin.isNull());auto& target=window.addEmptyProject(true);REQUIRE(!target.document&&command(window,"Paste")->isEnabled());command(window,"Paste")->trigger();finishPaste(window);REQUIRE(target.document&&target.document->layers.size()==1&&target.document->width==d.width&&target.document->height==d.height);const auto& pasted=activeLayer(target);REQUIRE(pasted.textJson==captured.textJson&&pasted.effectsJson==captured.effectsJson&&pasted.raster==captured.raster&&pasted.mask==captured.mask);REQUIRE(pasted.transform.fromUnit({.5,.5})==Point{320,210});}
void clipboardSnapshotCrossProject(){MainWindow window(true);auto d=clipboardFixture();const auto captured=d.layers[0];auto& source=window.addProject(d);command(window,"Copy")->trigger();Document destination;destination.id=newId();destination.width=800;destination.height=500;auto& target=window.addProject(destination);command(window,"Paste")->trigger();QApplication::clipboard()->setText("replaced while paste works");source.document->layers.clear();finishPaste(window);REQUIRE(target.document->layers.size()==1&&target.history.undoCount()==1&&source.document->layers.empty());const auto& pasted=activeLayer(target);REQUIRE(pasted.textJson==captured.textJson&&pasted.effectsJson==captured.effectsJson&&pasted.raster==captured.raster&&pasted.mask==captured.mask);REQUIRE(pasted.transform.fromUnit({.5,.5})==Point{400,250});}
void foldedTransforms(){namespace t=editing_transform;const Transform transform{0,0,8,8};const t::Corners shape{{{0,0},{8,8},{8,0},{0,8}}};REQUIRE(t::usableCorners(shape)&&!t::convexCorners(shape));const auto warped=t::warpRaster(Raster::filled(8,8,{64,0,0,128}),transform,shape);REQUIRE(warped.raster->width==8&&warped.raster->height==8);bool overlap=false,clear=false;for(int y=0;y<8;++y)for(int x=0;x<8;++x){const auto p=warped.raster->pixel(x,y);overlap|=p.a>128;clear|=p.a==0;}REQUIRE(overlap&&clear);Layer layer;layer.id=newId();layer.raster=Raster::filled(8,8,{64,0,0,128});layer.transform=transform;auto selection=std::make_shared<GrayRaster>(GrayRaster{8,8,std::vector<uint8_t>(64,255)});t::PixelTransformSession session(layer,selection,t::PixelTransformKind::Affine);REQUIRE(session.begin()&&session.update(transform,shape));auto changed=session.apply();REQUIRE(changed.selection->pixel(6,4)==255&&changed.selection->pixel(1,5)==255&&changed.selection->pixel(1,7)==0);t::Drag resize{{0,0,100,80},{100,80},{t::ModeKind::Resize,4}};const auto mirrored=resize.updated({-50,-40},true);REQUIRE(mirrored.flipX&&mirrored.flipY&&std::abs(mirrored.width-50)<1e-8&&std::abs(mirrored.height-40)<1e-8);REQUIRE(mirrored.fromUnit({0,0})==Point{0,0});}
void canvasExtend(){MainWindow window(true);Document d;d.id=newId();Layer first;first.id=newId();first.raster=Raster::filled(100,100,{100,100,100,255});first.transform={20,20,100,100};auto second=first;second.id=newId();second.transform.x=220;d.layers={first,second};auto& p=window.addProject(d);p.active=first.id;p.selected={first.id};command(window,"Move (V)")->trigger();window.findChild<QCheckBox*>("transformShowControls")->setChecked(false);const auto flags=Qt::ControlModifier|Qt::ShiftModifier;p.canvas->pointerDown({250,50},flags);p.canvas->pointerUp({250,50},flags);REQUIRE(p.selected.size()==2&&p.active==second.id);p.canvas->pointerDown({250,50},flags);p.canvas->pointerUp({250,50},flags);REQUIRE(p.selected==std::vector<std::string>{first.id}&&p.active==first.id&&p.history.undoCount()==0);}
void capture(const QString& directory){QDir().mkpath(directory);MainWindow window(true);auto d=fixture();auto style=sample();style.content="Editable typography\nWindows preview";style.fontSize=38;style.red=.92;style.green=.82;style.blue=.25;style.boxSize=QSizeF(530,180);d.layers[0]=editing::createTextLayer({40,95},style);auto& p=window.addProject(d);window.show();QTest::qWait(700);p.canvas->fit();QTest::qWait(250);REQUIRE(p.canvas->deviceReady());REQUIRE(p.canvas->captureRendered().save(directory+"/text-canvas.png"));command(window,"Edit Text Layer…")->trigger();QTest::qWait(400);auto* panel=window.findChild<QDialog*>("textEditorPanel");REQUIRE(panel&&panel->grab().save(directory+"/text-controls.png"));panel->reject();}
}
int main(int argc,char**argv){QApplication app(argc,argv);if(argc>2&&std::string(argv[1])=="capture"){try{capture(QString::fromLocal8Bit(argv[2]));return 0;}catch(const std::exception& error){std::cerr<<error.what();return 1;}}std::map<std::string,void(*)()> tests{{"metadata",metadata},{"layout",layout},{"transform",transform},{"operations",operations},{"roundtrip",roundtrip},{"lifecycle",lifecycle},{"creation",creation},{"clipped_transfer",clippedTransfer},{"lines",lines},{"line_creation",lineCreation},{"duplicate_group",duplicateGroup},{"clipboard_layers",clipboardLayers},{"clipboard_snapshot_edit",clipboardSnapshotEdit},{"clipboard_snapshot_delete",clipboardSnapshotDelete},{"clipboard_snapshot_close",clipboardSnapshotClose},{"clipboard_snapshot_cross_project",clipboardSnapshotCrossProject},{"folded_transforms",foldedTransforms},{"canvas_extend",canvasExtend}};int failed=0;for(const auto&[name,test]:tests){if(argc>1&&name!=argv[1])continue;try{test();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& error){++failed;std::cout<<"FAIL "<<name<<": "<<error.what()<<'\n';}}return failed?1:0;}
