// Editable Photoshop metadata conversion, based on the supported subset in
// Compositor v1.2.11 PSDText.swift/PSDVector.swift (MIT, Wonder Assembly LLC).
#include "psd_metadata.h"
#include "editing/Shapes.h"
#include "editing/Text.h"
#include "effects/Adjustments.h"
#include "effects_tools/Levels.h"
#include "effects_tools/Curves.h"
#include "effects_tools/Hue.h"
#include <QVariant>
#include <QJsonArray>
#include <QJsonObject>
#include <QJsonDocument>
#include <QPainterPath>
#include <QPainter>
#include <QFontDatabase>
#include <QImage>
#include <bit>
#include <cmath>
#include <numbers>
namespace compositor::imaging {
namespace {
struct Reader {
    QByteArray bytes;qsizetype at{};int nodes{};
    void need(qsizetype n){if(n<0||at>bytes.size()-n)throw std::runtime_error("Damaged Photoshop metadata");}
    uint8_t u8(){need(1);return uint8_t(bytes[at++]);}
    uint16_t u16(){auto a=u8();return uint16_t(a<<8|u8());}
    uint32_t u32(){auto a=u16();return uint32_t(a)<<16|u16();}
    double f64(){const auto a=u32();const auto b=u32();return std::bit_cast<double>(uint64_t(a)<<32|b);}
    QByteArray raw(qsizetype n){need(n);auto result=bytes.mid(at,n);at+=n;return result;}
    QString unicode(){const auto n=u32();if(n>1000000)throw std::runtime_error("Photoshop metadata string exceeds budget");QString s;for(uint32_t i=0;i<n;++i)s+=QChar(u16());while(s.endsWith(QChar(0)))s.chop(1);return s;}
    QString key(){const auto n=u32();return QString::fromLatin1(raw(n?n:4));}
    QVariant value(QByteArray type,int depth){if(++nodes>20000||depth>40)throw std::runtime_error("Photoshop metadata nesting exceeds budget");if(type=="doub")return f64();if(type=="UntF"){raw(4);return f64();}if(type=="long")return int32_t(u32());if(type=="bool")return u8()!=0;if(type=="TEXT")return unicode();if(type=="enum"){key();return key();}if(type=="tdta"||type=="alis")return raw(u32());if(type=="Objc"||type=="GlbO")return descriptor(false,depth+1);if(type=="VlLs"){const auto n=u32();if(n>10000)throw std::runtime_error("Photoshop metadata list exceeds budget");QVariantList list;for(uint32_t i=0;i<n;++i)list.append(value(raw(4),depth+1));return list;}if(type=="comp"){const auto hi=u32(),lo=u32();return double(int64_t(uint64_t(hi)<<32|lo));}throw std::runtime_error("Unsupported Photoshop descriptor value");}
    QVariantMap descriptor(bool versioned,int depth=0){if(versioned&&u32()!=16)throw std::runtime_error("Unsupported Photoshop descriptor version");unicode();key();const auto n=u32();if(n>10000)throw std::runtime_error("Photoshop metadata fields exceed budget");QVariantMap result;for(uint32_t i=0;i<n;++i){auto k=key();auto type=raw(4);result[k]=value(type,depth+1);}return result;}
};
QString engineString(QByteArray bytes){if(bytes.startsWith(QByteArray::fromHex("feff"))){Reader r{bytes};r.at=2;QString out;while(r.at+2<=bytes.size())out+=QChar(r.u16());return out;}return QString::fromLatin1(bytes);}
struct Engine {
    QByteArray bytes;qsizetype at{};int nodes{};
    void ws(){while(at<bytes.size()){if(bytes[at]=='%'){while(at<bytes.size()&&bytes[at]!='\n')++at;}else if(uint8_t(bytes[at])<=32)++at;else break;}}
    bool take(const char* s){const QByteArray token(s);if(bytes.mid(at,token.size())!=token)return false;at+=token.size();return true;}
    QString token(){const auto start=at;while(at<bytes.size()&&uint8_t(bytes[at])>32&&!QByteArray("/<>[]()").contains(bytes[at]))++at;if(start==at)throw std::runtime_error("Invalid Photoshop text engine token");return QString::fromLatin1(bytes.mid(start,at-start));}
    QVariant parse(int depth=0){if(++nodes>20000||depth>40)throw std::runtime_error("Photoshop text engine exceeds budget");ws();if(at>=bytes.size())throw std::runtime_error("Truncated Photoshop text engine");if(take("<<")){QVariantMap map;for(;;){ws();if(take(">>"))return map;if(!take("/"))throw std::runtime_error("Invalid Photoshop text dictionary");auto key=token();map[key]=parse(depth+1);}}if(take("[")){QVariantList list;for(;;){ws();if(take("]"))return list;list.append(parse(depth+1));}}if(take("(")){QByteArray out;int nested=1;while(at<bytes.size()){char c=bytes[at++];if(c==')'&&!--nested)return engineString(out);if(c=='(')++nested;if(c=='\\'){if(at>=bytes.size())break;c=bytes[at++];if(c>='0'&&c<='7'){int n=c-'0';for(int i=0;i<2&&at<bytes.size()&&bytes[at]>='0'&&bytes[at]<='7';++i)n=n*8+bytes[at++]-'0';out+=char(n);continue;}if(c=='n')c='\n';else if(c=='r')c='\r';else if(c=='t')c='\t';else if(c=='\r'||c=='\n')continue;}out+=c;}throw std::runtime_error("Truncated Photoshop text string");}if(take("<")){auto end=bytes.indexOf('>',at);if(end<0)throw std::runtime_error("Truncated Photoshop text hex string");auto out=QByteArray::fromHex(bytes.mid(at,end-at));at=end+1;return engineString(out);}if(take("/"))return token();auto word=token();if(word=="true")return true;if(word=="false")return false;if(word=="null")return QVariant();bool ok=false;double n=word.toDouble(&ok);if(!ok||!std::isfinite(n))throw std::runtime_error("Invalid Photoshop text number");return n;}
};
QVariant walk(QVariant v,std::initializer_list<const char*> names){for(auto name:names)v=v.toMap().value(QLatin1String(name));return v;}
double number(const QVariantMap& m,const char* k,double fallback=0){const auto v=m.value(QLatin1String(k));return v.isValid()?v.toDouble():fallback;}
double unit(double v){return std::clamp(v>1?v/255:v,0.,1.);}
std::optional<QJsonObject> textStyle(const QByteArray& bytes,QStringList& notes,Point& anchor,double& rotation,bool& flipY,bool& frame){
    Reader r{bytes};if(r.u16()!=1)return {};const auto xx=r.f64(),xy=r.f64(),yx=r.f64(),yy=r.f64(),tx=r.f64(),ty=r.f64();for(auto v:{xx,xy,yx,yy,tx,ty})if(!std::isfinite(v))return {};const double sx=std::hypot(xx,yx);if(sx<1e-6)return {};const double cosine=xx/sx,sine=yx/sx,localX=cosine*xy+sine*yy,localY=-sine*xy+cosine*yy,sy=std::abs(localY);if(sy<1e-6||std::abs(localX)>.02*std::max(sx,sy)||std::abs(sx-sy)>.02*std::max(sx,sy))return {};
    anchor={tx,ty};rotation=std::atan2(sine,cosine)*180/std::numbers::pi;flipY=localY<0;frame=false;if(r.u16()!=50)return {};const auto descriptor=r.descriptor(true);if(descriptor.value("Ornt").toString()=="Vrtc")return {};QVariant engine;const auto engineData=descriptor.value("EngineData").toByteArray();if(!engineData.isEmpty()){Engine parser{engineData};parser.at=std::max<qsizetype>(0,engineData.indexOf("<<"));engine=parser.parse();}
    QString content=descriptor.value("Txt ",descriptor.value("Txt")).toString();if(content.isEmpty())content=walk(engine,{"EngineDict","Editor","Text"}).toString();while(!content.isEmpty()&&(content.front()==QChar(0xfeff)||content.front()==QChar(0)))content.remove(0,1);content.replace("\r\n","\n").replace('\r','\n');while(content.endsWith(QChar(0)))content.chop(1);if(content.isEmpty()||content.size()>100000)return {};
    const auto runs=walk(engine,{"EngineDict","StyleRun","RunArray"}).toList();const auto first=runs.isEmpty()?engine:runs.first();auto data=walk(first,{"StyleSheet","StyleSheetData"}).toMap();if(data.isEmpty())data=first.toMap();const auto fonts=walk(engine,{"ResourceDict","FontSet"}).toList();const auto fontIndex=int(std::round(number(data,"Font")));QString font="Arial";if(fontIndex>=0&&fontIndex<fonts.size())font=fonts[fontIndex].toMap().value("Name").toString();const double size=std::clamp(number(data,"FontSize",12)*sx,1.,2000.);auto colors=walk(data,{"FillColor","Values"}).toList();double red=0,green=0,blue=0;if(colors.size()>=3){int i=colors.size()>=4?1:0;red=unit(colors[i].toDouble());green=unit(colors[i+1].toDouble());blue=unit(colors[i+2].toDouble());}else if(!colors.isEmpty())red=green=blue=unit(colors[0].toDouble());
    const auto paragraphs=walk(engine,{"EngineDict","ParagraphRun","RunArray"}).toList();int justification=int(walk(paragraphs.isEmpty()?engine:paragraphs.first(),{"ParagraphSheet","Properties","Justification"}).toDouble());if(justification>2)notes.append("Full justification was imported as left alignment.");if(data.value("FauxBold").toBool()||data.value("FauxItalic").toBool())notes.append("Faux bold or faux italic was omitted.");if(runs.size()>1&&std::any_of(runs.begin()+1,runs.end(),[&](const QVariant& v){return v!=runs.front();}))notes.append("Only the first text style was retained.");
    QJsonObject style{{"content",content},{"fontName",font},{"fontSize",size},{"red",red},{"green",green},{"blue",blue},{"alignment",justification==1?"Right":justification==2?"Center":"Left"},{"tracking",std::clamp(number(data,"Tracking")*size/1000,-100.,1000.)},{"leading",data.value("AutoLeading",true).toBool()?0:std::clamp(number(data,"Leading")*sx,0.,5000.)}};
    auto rect=[](QVariant value){auto m=value.toMap();const auto l=number(m,"Left"),t=number(m,"Top ",number(m,"Top")),right=number(m,"Rght"),bottom=number(m,"Btom");return QRectF(l,t,right-l,bottom-t);};const auto bounds=rect(descriptor.value("bounds")),glyphs=rect(descriptor.value("boundingBox"));if(bounds.width()>glyphs.width()+4&&bounds.height()>glyphs.height()+4&&bounds.width()>1&&bounds.height()>1){const double w=bounds.width()*sx+24,h=bounds.height()*sx+24;if(w>30000||h>30000||w*h>100000000)return {};style["boxSize"]=QJsonArray{w,h};const double sign=flipY?-1:1;anchor={cosine*sx*bounds.x()-sine*sx*sign*bounds.y()+tx,sine*sx*bounds.x()+cosine*sx*sign*bounds.y()+ty};frame=true;}
    if(r.at+2<bytes.size()&&r.u16()==1){auto warp=r.descriptor(true);const auto mode=warp.value("warpStyle").toString();if(!mode.isEmpty()&&mode!="warpNone"&&mode!="none")notes.append("The Photoshop text warp was omitted.");}
    return style;
}
std::optional<double> scalar(const QByteArray& bytes,const QByteArray& key,const QByteArray& type,int after=0){auto at=bytes.indexOf(key,after);if(at<0)return {};at+=key.size();if(bytes.mid(at,4)!=type)return {};Reader r{bytes};r.at=at+4;if(type=="UntF")r.raw(4);const double value=type=="long"?double(int32_t(r.u32())):type=="bool"?r.u8():r.f64();if(!std::isfinite(value))return {};return value;}
QColor rgb(const QByteArray& data){const auto r=scalar(data,"Rd  ","doub"),g=scalar(data,"Grn ","doub"),b=scalar(data,"Bl  ","doub");return r&&g&&b?QColor::fromRgbF(unit(*r),unit(*g),unit(*b)):QColor();}
QPainterPath vectorPath(const QByteArray& bytes,int width,int height){Reader r{bytes};r.at=8;QPainterPath path;QPointF first,firstIn,previousOut;int remaining=0;bool closed=true,started=false;auto finish=[&]{if(started&&closed){path.cubicTo(previousOut,firstIn,first);path.closeSubpath();}started=false;};auto point=[&](Reader& item){const auto y=double(int32_t(item.u32()))/16777216.,x=double(int32_t(item.u32()))/16777216.;return QPointF(x*width,y*height);};while(r.at+26<=bytes.size()){auto type=r.u16();Reader item{r.raw(24)};if(type==0||type==3){finish();remaining=item.u16();closed=type==0;}else if((type==1||type==2||type==4||type==5)&&remaining>0){--remaining;const auto incoming=point(item),anchor=point(item),outgoing=point(item);if(!started){first=anchor;firstIn=incoming;path.moveTo(anchor);started=true;}else path.cubicTo(previousOut,incoming,anchor);previousOut=outgoing;}}finish();path.setFillRule(Qt::WindingFill);return path;}
bool shape(Layer& layer,const PhotoshopExtras& extra,int width,int height,QStringList& notes,const ImportOptions& options){
    const auto stroke=extra.value("vstk"),origin=extra.value("vogk");const bool fill=scalar(stroke,"fillEnabled","bool").value_or(extra.contains("SoCo")?1:0)!=0,hasStroke=scalar(stroke,"strokeEnabled","bool").value_or(0)!=0;auto color=rgb(extra.value("SoCo"));const auto kind=int(scalar(origin,"keyOriginType","long").value_or(0));QRectF bounds;editing::ShapeStyle style;bool live=false;
    if(fill&&color.isValid()&&(kind==1||kind==2||kind==5)){const auto at=int(std::max<qsizetype>(0,origin.indexOf("keyOriginShapeBBox")));const auto l=scalar(origin,"Left","UntF",at),t=scalar(origin,"Top ","UntF",at),right=scalar(origin,"Rght","UntF",at),bottom=scalar(origin,"Btom","UntF",at);if(l&&t&&right&&bottom){bounds={*l,*t,*right-*l,*bottom-*t};style.kind=kind==5?editing::ShapeKind::Ellipse:editing::ShapeKind::Rectangle;live=true;if(kind==2){std::array<double,4> radii{};int i=0;for(const auto* key:{"topLeft","topRight","bottomRight","bottomLeft"})radii[size_t(i++)]=scalar(origin,key,"UntF").value_or(0);auto [lo,hi]=std::minmax_element(radii.begin(),radii.end());if(*hi-*lo>.5)live=false;else style.cornerRadius=*hi;}}}
    auto path=vectorPath(extra.value("vmsk",extra.value("vsms")),width,height);
    if(!live&&fill&&color.isValid()&&path.elementCount()==13){const auto b=path.boundingRect();bool rectangle=true;for(int i=0;i<path.elementCount();++i){const auto p=path.elementAt(i);if(std::min(std::abs(p.x-b.left()),std::abs(p.x-b.right()))>.5||std::min(std::abs(p.y-b.top()),std::abs(p.y-b.bottom()))>.5){rectangle=false;break;}}if(rectangle){live=true;bounds=b;}}
    if(live&&bounds.width()>=1&&bounds.height()>=1){bounds=bounds.toAlignedRect();checkedBytes(uint32_t(bounds.width()),uint32_t(bounds.height()),4,options);style.red=color.redF();style.green=color.greenF();style.blue=color.blueF();layer.raster=editing::shapeRaster(style,int(bounds.width()),int(bounds.height()));layer.shapeJson=editing::encodeShapeStyle(style);layer.transform={bounds.x(),bounds.y(),bounds.width(),bounds.height()};if(hasStroke)notes.append("The Photoshop vector stroke was omitted.");return true;}
    if(!layer.raster&&!path.isEmpty()&&((fill&&color.isValid())||hasStroke)){const auto strokeColor=rgb(stroke);double strokeWidth=scalar(stroke,"strokeStyleLineWidth","UntF").value_or(1);bounds=path.boundingRect();if(hasStroke)bounds.adjust(-strokeWidth/2-1,-strokeWidth/2-1,strokeWidth/2+1,strokeWidth/2+1);bounds=bounds.toAlignedRect();checkedBytes(uint32_t(bounds.width()),uint32_t(bounds.height()),4,options);QImage image(bounds.size().toSize(),QImage::Format_RGBA8888_Premultiplied);image.fill(Qt::transparent);QPainter painter(&image);painter.setRenderHint(QPainter::Antialiasing);painter.translate(-bounds.topLeft());painter.setBrush(fill?QBrush(color):QBrush(Qt::NoBrush));painter.setPen(hasStroke?QPen(strokeColor,strokeWidth):QPen(Qt::NoPen));painter.drawPath(path);painter.end();layer.raster=Raster::fromRgba(image.width(),image.height(),image.constBits(),image.bytesPerLine());layer.transform={bounds.x(),bounds.y(),bounds.width(),bounds.height()};}return false;
}
bool adjustment(Layer& layer,const PhotoshopExtras& extra){
    if(extra.contains("levl")){Reader r{extra["levl"]};if(r.bytes.size()<292)return false;r.u16();effects_tools::LevelsSettings settings;for(size_t c=0;c<4;++c){auto& s=settings.ranges[c];s.black=r.u16();s.white=r.u16();s.outputBlack=r.u16();s.outputWhite=r.u16();s.gamma=r.u16()/256.;}layer.adjustmentJson=effects_tools::withLevelsSettings(effects::defaultAdjustmentJson("Levels"),settings);return true;}
    if(extra.contains("curv")){Reader r{extra["curv"]};if(r.bytes.size()<5)return false;if(r.bytes[0]==0)r.u8();const auto version=r.u16();if(version!=1&&version!=4)return false;auto count=r.u16();effects_tools::CurvesSettings settings;for(unsigned c=0;c<std::min<unsigned>(4,count);++c){const auto n=r.u16();if(n>32)return false;std::vector<Point> curve;for(unsigned p=0;p<n;++p){auto y=r.u16(),x=r.u16();curve.push_back({double(std::min<unsigned>(255,x)),double(std::min<unsigned>(255,y))});}if(curve.size()<2)continue;std::sort(curve.begin(),curve.end(),[](auto a,auto b){return a.x<b.x;});if(curve.front().x>0)curve.insert(curve.begin(),{0,curve.front().y});if(curve.back().x<255)curve.push_back({255,curve.back().y});settings.channels[c]=std::move(curve);}layer.adjustmentJson=effects_tools::withCurvesSettings(effects::defaultAdjustmentJson("Curves"),settings);return true;}
    if(extra.contains("hue2")||extra.contains("hue ")){Reader r{extra.value("hue2",extra.value("hue "))};r.u16();effects_tools::HueSettings settings;settings.colorize=r.u8()!=0;r.u8();for(size_t c=0;c<7&&r.at+6<=r.bytes.size();++c){auto& s=settings.adjustments[c];s.hue=int16_t(r.u16());s.saturation=int16_t(r.u16());s.lightness=int16_t(r.u16());}layer.adjustmentJson=effects_tools::withHueSettings(effects::defaultAdjustmentJson("Hue/Saturation"),settings);return true;}return false;
}
}
void applyPhotoshopMetadata(Layer& layer,const PhotoshopExtras& extra,int canvasWidth,int canvasHeight,QStringList& conversions,const ImportOptions& options){
    QStringList notes;
    if(extra.contains("TySh")||extra.contains("tySh")||extra.contains("txt2")){try{Point anchor;double rotation=0;bool flipY=false,frame=false;const auto style=textStyle(extra.value("TySh",extra.value("tySh")),notes,anchor,rotation,flipY,frame);if(style){auto json=QJsonDocument(*style).toJson(QJsonDocument::Compact).toStdString();auto parsed=editing::decodeTextStyle(json);auto size=editing::textBoxSize(parsed);checkedBytes(uint32_t(std::ceil(size.width())),uint32_t(std::ceil(size.height())),4,options);auto raster=editing::textRaster(parsed);Point local{frame?12:parsed.alignment==editing::TextAlignment::Right?raster->width-12:parsed.alignment==editing::TextAlignment::Center?raster->width/2.:12,frame?12:editing::textFirstBaseline(parsed)};Transform placement{0,0,double(raster->width),double(raster->height),rotation,false,flipY};auto mapped=placement.fromUnit({local.x/raster->width,local.y/raster->height});placement.x=anchor.x-mapped.x;placement.y=anchor.y-mapped.y;layer.textJson=json;layer.raster=raster;layer.transform=placement;if(!QFontDatabase::families().contains(style->value("fontName").toString()))notes.append("The original font may require substitution when text is edited on Windows.");}else notes.append("Unsupported editable Photoshop text was kept as pixels.");}catch(const std::exception&){notes.append("Unsupported editable Photoshop text was kept as pixels.");}}
    else if(extra.contains("vmsk")||extra.contains("vsms")||extra.contains("vogk")){bool editable=false;try{editable=shape(layer,extra,canvasWidth,canvasHeight,notes,options);}catch(const std::exception&){if(!layer.raster)throw;}if(!editable)notes.append("Vector shape was imported as pixels.");}
    else if(extra.contains("SoLd")||extra.contains("SoLE"))notes.append("The smart object was rasterized; linked contents cannot be edited.");
    if(!layer.group){static const QList<QByteArray> keys{"levl","curv","hue2","hue ","expA","grdm","brit","blnc","nvrt","thrs","post","mixr","selc","blwh","phfl","vibA"};bool has=false;for(const auto& k:keys)has|=extra.contains(k);if(has){bool converted=false;try{converted=adjustment(layer,extra);}catch(const std::exception&){}if(converted){layer.raster.reset();layer.transform={0,0,double(canvasWidth),double(canvasHeight)};notes.append("Adjustment parameters may differ from Photoshop.");}else{conversions.append(QString::fromStdString(layer.name)+": Unsupported Photoshop adjustment was skipped.");layer.name.clear();return;}}}
    for(const auto& note:notes)conversions.append(QString::fromStdString(layer.name)+": "+note);
}
}
