# Pinned source dependencies are populated by bootstrap-imports.ps1. LibRaw is
# used under CDDL-1.0; unchanged source and notices accompany each package.
set(import_zlib_root "${CMAKE_SOURCE_DIR}/dependencies/zlib/zlib-1.3.1")
set(import_raw_root "${CMAKE_SOURCE_DIR}/dependencies/libraw/LibRaw-0.21.5")
if(NOT EXISTS "${import_raw_root}/libraw/libraw.h" OR NOT EXISTS "${import_zlib_root}/zlib.h")
  message(FATAL_ERROR "Run scripts/bootstrap-imports.ps1 to populate locked RAW/PSD dependencies")
endif()
set(import_zlib_sources adler32.c compress.c crc32.c deflate.c infback.c inffast.c inflate.c inftrees.c trees.c uncompr.c zutil.c)
list(TRANSFORM import_zlib_sources PREPEND "${import_zlib_root}/")
add_library(compositor_zlib STATIC ${import_zlib_sources})
target_include_directories(compositor_zlib PUBLIC "${import_zlib_root}")
target_compile_definitions(compositor_zlib PRIVATE _CRT_SECURE_NO_WARNINGS)
file(GLOB_RECURSE import_raw_sources CONFIGURE_DEPENDS "${import_raw_root}/src/*.cpp")
list(FILTER import_raw_sources EXCLUDE REGEX "_ph\\.cpp$")
add_library(compositor_raw STATIC ${import_raw_sources})
target_include_directories(compositor_raw PUBLIC "${import_raw_root}")
target_compile_definitions(compositor_raw PUBLIC LIBRAW_NODLL PRIVATE USE_ZLIB _CRT_SECURE_NO_WARNINGS NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(compositor_raw PRIVATE /utf-8)
target_link_libraries(compositor_raw PRIVATE compositor_zlib ws2_32)
