// Camera Raw kernels and order mirror CameraRaw*.swift at v1.2.11.
// Copyright (c) 2026 Wonder Assembly LLC, MIT (graphics/upstream/LICENSE).
#include "CameraRaw.h"
#include "effects_tools/CurveMath.h"
extern "C" {
#include "graphics/upstream/AdjustPixels.h"
}
#include <QImage>
#include <QPainter>
#include <QPolygonF>
#include <QTransform>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <cmath>
#include <numbers>
#include <limits>
namespace compositor::effects {
const std::vector<CameraRawParameter>& cameraRawParameters(){static const auto parameters=[] {
    std::vector<CameraRawParameter> p;auto add=[&](const char*g,const char*k,const char*l,double lo=-100,double hi=100,double initial=0){p.push_back({g,k,l,lo,hi,initial});};
    add("Light","exposure","Exposure",-5,5);for(auto pair:{std::pair{"contrast","Contrast"},{"highlights","Highlights"},{"shadows","Shadows"},{"whites","Whites"},{"blacks","Blacks"}})add("Light",pair.first,pair.second);
    for(auto pair:{std::pair{"temperature","Temperature"},{"tint","Tint"},{"vibrance","Vibrance"},{"saturation","Saturation"}})add("Color",pair.first,pair.second);
    for(auto pair:{std::pair{"texture","Texture"},{"clarity","Clarity"},{"dehaze","Dehaze"},{"glowRange","Glow range"},{"glowSpread","Glow spread"},{"glowWarmth","Glow warmth"},{"vignetteAmount","Vignette amount"},{"vignetteRoundness","Vignette roundness"}})add("Effects",pair.first,pair.second);
    add("Effects","glow","Glow",0,100);add("Effects","glowStyle","Glow style",0,2);add("Effects","vignetteStyle","Vignette style",0,2);add("Effects","vignetteMidpoint","Vignette midpoint",0,100,50);add("Effects","vignetteFeather","Vignette feather",0,100,50);add("Effects","vignetteHighlights","Vignette highlights",0,100);add("Effects","grainAmount","Grain amount",0,100);add("Effects","grainSize","Grain size",0,100,25);add("Effects","grainRoughness","Grain roughness",0,100,50);
    add("Curve","curveShadows","Shadows");add("Curve","curveDarks","Darks");add("Curve","curveLights","Lights");add("Curve","curveHighlights","Highlights");add("Curve","shadowSplit","Shadow split",5,90,25);add("Curve","darkSplit","Dark split",7,95,50);add("Curve","lightSplit","Light split",9,98,75);add("Curve","refineSaturation","Refine saturation",-100,100);
    static const char* mixerKeys[3][8]={{"redHue","orangeHue","yellowHue","greenHue","aquaHue","blueHue","purpleHue","magentaHue"},{"redSaturation","orangeSaturation","yellowSaturation","greenSaturation","aquaSaturation","blueSaturation","purpleSaturation","magentaSaturation"},{"redLuminance","orangeLuminance","yellowLuminance","greenLuminance","aquaLuminance","blueLuminance","purpleLuminance","magentaLuminance"}};
    static const char* mixerLabels[3][8]={{"Red hue","Orange hue","Yellow hue","Green hue","Aqua hue","Blue hue","Purple hue","Magenta hue"},{"Red saturation","Orange saturation","Yellow saturation","Green saturation","Aqua saturation","Blue saturation","Purple saturation","Magenta saturation"},{"Red luminance","Orange luminance","Yellow luminance","Green luminance","Aqua luminance","Blue luminance","Purple luminance","Magenta luminance"}};
    for(int a=0;a<3;++a)for(int c=0;c<8;++c)add("Mixer",mixerKeys[a][c],mixerLabels[a][c]);
    static const char* gradeKeys[4][3]={{"gradeShadowHue","gradeShadowSaturation","gradeShadowLuminance"},{"gradeMidtoneHue","gradeMidtoneSaturation","gradeMidtoneLuminance"},{"gradeHighlightHue","gradeHighlightSaturation","gradeHighlightLuminance"},{"gradeGlobalHue","gradeGlobalSaturation","gradeGlobalLuminance"}};
    static const char* gradeLabels[4][3]={{"Shadows hue","Shadows saturation","Shadows luminance"},{"Midtones hue","Midtones saturation","Midtones luminance"},{"Highlights hue","Highlights saturation","Highlights luminance"},{"Global hue","Global saturation","Global luminance"}};
    for(int wheel=0;wheel<4;++wheel)for(int c=0;c<3;++c)add("Grading",gradeKeys[wheel][c],gradeLabels[wheel][c],c==2?-100:0,c==0?360:100);add("Grading","gradeBlending","Blending",0,100,50);add("Grading","gradeBalance","Balance");
    add("Detail","sharpenAmount","Sharpening amount",0,150);add("Detail","sharpenRadius","Sharpening radius",0,100,10);add("Detail","sharpenDetail","Sharpening detail",0,100,25);add("Detail","sharpenMasking","Sharpening masking",0,100);add("Detail","noiseLuminance","Noise luminance",0,100);add("Detail","noiseLuminanceDetail","Luminance detail",0,100,50);add("Detail","noiseLuminanceContrast","Luminance contrast",0,100);add("Detail","noiseColor","Color noise",0,100);add("Detail","noiseColorDetail","Color detail",0,100,50);add("Detail","noiseColorSmoothness","Color smoothness",0,100,50);
    add("Optics","removeChromatic","Remove chromatic aberration",0,1);add("Optics","lensProfile","Enable generic lens correction",0,1);add("Optics","profileDistortion","Profile distortion",0,100,100);add("Optics","profileVignetting","Profile vignetting",0,100,100);add("Optics","distortion","Distortion");add("Optics","purpleAmount","Purple defringe",0,100);add("Optics","purpleHueLow","Purple hue start",0,360,270);add("Optics","purpleHueHigh","Purple hue end",0,360,310);add("Optics","greenAmount","Green defringe",0,100);add("Optics","greenHueLow","Green hue start",0,360,60);add("Optics","greenHueHigh","Green hue end",0,360,120);add("Optics","opticsVignette","Lens vignette");add("Optics","opticsMidpoint","Lens vignette midpoint",0,100,50);
    add("Geometry","upright","Guided upright",0,1);add("Geometry","projection","Rectilinear projection",0,1);add("Geometry","vertical","Vertical");add("Geometry","horizontal","Horizontal");add("Geometry","rotate","Rotate",-45,45);add("Geometry","aspect","Aspect");add("Geometry","scale","Scale");add("Geometry","offsetX","Horizontal offset");add("Geometry","offsetY","Vertical offset");add("Geometry","constrainCrop","Constrain crop",0,1);
    add("Calibration","process","Process version",1,6,6);add("Calibration","shadowTint","Shadow tint");add("Calibration","primaryRedHue","Red primary hue");add("Calibration","primaryRedSaturation","Red primary saturation");add("Calibration","primaryGreenHue","Green primary hue");add("Calibration","primaryGreenSaturation","Green primary saturation");add("Calibration","primaryBlueHue","Blue primary hue");add("Calibration","primaryBlueSaturation","Blue primary saturation");return p;
}();return parameters;}
CameraRawSettings::CameraRawSettings(){for(const auto& p:cameraRawParameters())values[p.key]=p.initial;for(auto& curve:curves)curve={{0,0},{255,255}};}
double CameraRawSettings::get(std::string_view key)const{auto found=values.find(key);if(found==values.end())throw std::runtime_error("Unknown Camera Raw setting");return found->second;}
void CameraRawSettings::set(std::string_view key,double value){auto found=std::find_if(cameraRawParameters().begin(),cameraRawParameters().end(),[&](const auto& p){return key==p.key;});if(found==cameraRawParameters().end()||!std::isfinite(value)||value<found->minimum||value>found->maximum)throw std::runtime_error("Invalid Camera Raw setting");values[std::string(key)]=value;}
bool CameraRawSettings::identity()const{CameraRawSettings neutral;return values==neutral.values&&curves==neutral.curves&&points.empty()&&guides.empty();}
namespace {
QImage geometry(const QImage& input,const CameraRawSettings& s){
    double vertical=s.get("vertical"),horizontal=s.get("horizontal"),rotation=s.get("rotate");if(s.get("upright")&&!s.guides.empty()){auto [a,b]=s.guides[0];const auto dx=b.x-a.x,dy=b.y-a.y;if(std::hypot(dx,dy)>.01){double angle=-std::atan2(dy,dx)*180/std::numbers::pi;if(angle>45)angle-=90;else if(angle< -45)angle+=90;rotation+=angle;}if(s.guides.size()>1){auto [c,d]=s.guides[1];double angle=std::atan2(d.y-c.y,d.x-c.x)*180/std::numbers::pi;if(std::hypot(d.y-c.y,d.x-c.x)>.01){if(std::abs(angle)>45)vertical+=angle>0?25:-25;else horizontal+=angle>0?25:-25;}}}
    if(vertical==0&&horizontal==0&&rotation==0&&s.get("aspect")==0&&s.get("scale")==0&&s.get("offsetX")==0&&s.get("offsetY")==0)return input;
    const double w=input.width(),h=input.height(),strength=s.get("projection")?.55:1,v=vertical/100*w*.18*strength,hz=horizontal/100*h*.18*strength,shiftX=s.get("offsetX")/100*w*.15,shiftY=s.get("offsetY")/100*h*.15,cx=w/2+shiftX,cy=h/2+shiftY,aspect=1+s.get("aspect")/200,zoom=1+s.get("scale")/100,rad=rotation*std::numbers::pi/180;
    QPolygonF quad;for(auto [x,y]:{Point{-v+shiftX,h+shiftY},Point{w+v+shiftX,h+shiftY},Point{w+hz+shiftX,-shiftY},Point{-hz+shiftX,-shiftY}}){const double dx=x-cx,dy=y-cy,rx=cx+dx*std::cos(rad)-dy*std::sin(rad),ry=cy+dx*std::sin(rad)+dy*std::cos(rad);quad<<QPointF(cx+(rx-cx)*aspect*zoom,h-(cy+(ry-cy)/aspect*zoom));}
    if(zoom<=0){QImage blank(input.size(),input.format());blank.fill(Qt::transparent);return blank;}QTransform transform;if(!QTransform::quadToQuad(QPolygonF{QPointF(0,0),QPointF(w,0),QPointF(w,h),QPointF(0,h)},quad,transform))return input;QImage output(input.size(),input.format());output.fill(Qt::transparent);QPainter p(&output);p.setRenderHint(QPainter::SmoothPixmapTransform);p.setTransform(transform);p.drawImage(0,0,input);p.end();
    if(s.get("constrainCrop")){int left=output.width(),top=output.height(),right=0,bottom=0;for(int y=0;y<output.height();++y){auto row=output.constScanLine(y);for(int x=0;x<output.width();++x)if(row[x*4+3]){left=std::min(left,x);top=std::min(top,y);right=std::max(right,x+1);bottom=std::max(bottom,y+1);}}if(right>left&&bottom>top&&(right-left<output.width()||bottom-top<output.height())){auto cropped=output.copy(left,top,right-left,bottom-top).scaled(output.size(),Qt::KeepAspectRatio,Qt::SmoothTransformation);output.fill(Qt::transparent);QPainter painter(&output);painter.drawImage((output.width()-cropped.width())/2,(output.height()-cropped.height())/2,cropped);}}
    return output;
}
}
std::shared_ptr<const Raster> applyCameraRaw(const Raster& image,const CameraRawSettings& s,double scale,CameraRawPreview view,std::function<bool()> cancelled){
    auto check=[&]{if(cancelled&&cancelled())throw std::runtime_error("Camera Raw cancelled");};check();if(!std::isfinite(scale)||scale<=0)throw std::runtime_error("Invalid Camera Raw preview scale");for(const auto& p:cameraRawParameters()){const auto v=s.get(p.key);if(!std::isfinite(v)||v<p.minimum||v>p.maximum)throw std::runtime_error("Invalid Camera Raw parameter");}for(const auto& curve:s.curves)if(!effects_tools::validCurve(curve))throw std::runtime_error("Invalid Camera Raw curve");if(s.points.size()>32||s.guides.size()>4)throw std::runtime_error("Camera Raw point/guide budget exceeded");if(s.identity()&&!view.clipping&&view.pointColor<0&&!view.sharpenMask&&!view.shadowOverlay&&!view.highlightOverlay)return std::make_shared<Raster>(image);
    auto bytes=image.rgba();QImage input(bytes.data(),image.width,image.height,image.width*4,QImage::Format_RGBA8888_Premultiplied);QImage output=(!view.clipping&&!view.sharpenMask&&view.pointColor<0?geometry(input,s):input).copy();auto* p=output.bits();const auto w=size_t(output.width()),h=size_t(output.height()),stride=size_t(output.bytesPerLine());auto v=[&](const char* key){return s.get(key);};
    if(!view.clipping&&!view.sharpenMask)adjust_camera_raw_calibration(p,w,h,stride,v("shadowTint"),v("primaryRedHue"),v("primaryRedSaturation"),v("primaryGreenHue"),v("primaryGreenSaturation"),v("primaryBlueHue"),v("primaryBlueSaturation"),int(v("process")));check();
    const auto warm=v("temperature")/100,magenta=v("tint")/100;adjust_camera_raw(p,w,h,stride,1+.35*warm+.15*magenta,1-.30*magenta,1-.35*warm+.15*magenta,v("exposure"),v("contrast"),v("highlights"),v("shadows"),v("whites"),v("blacks"),v("vibrance"),v("saturation"),view.clipping);check();
    if(!view.clipping&&!view.sharpenMask){std::array<std::array<float,256>,4> lut;std::array<double,3> splits{v("shadowSplit")/100,v("darkSplit")/100,v("lightSplit")/100};splits[0]=std::clamp(splits[0],.05,.90);splits[1]=std::clamp(splits[1],splits[0]+.02,.95);splits[2]=std::clamp(splits[2],splits[1]+.02,.98);std::array<double,5> edges{0,splits[0],splits[1],splits[2],1};std::array<double,4> amount{v("curveShadows"),v("curveDarks"),v("curveLights"),v("curveHighlights")};for(int i=0;i<256;++i){double tone=i/255.;int region=tone<edges[1]?0:tone<edges[2]?1:tone<edges[3]?2:3;const double lo=edges[size_t(region)],hi=edges[size_t(region+1)],weight=std::max(0.,1-std::abs(tone-(lo+hi)/2)/(std::max(.02,hi-lo)/2));lut[0][size_t(i)]=float(effects_tools::curveValueUnchecked(s.curves[0],std::clamp(tone+amount[size_t(region)]/100*weight*.22,0.,1.)*255)/255);for(int c=1;c<4;++c)lut[size_t(c)][size_t(i)]=float(effects_tools::curveValueUnchecked(s.curves[size_t(c)],i)/255);}
        std::array<float,24> mixer;size_t index=0;for(const auto* channel:{"Hue","Saturation","Luminance"})for(const auto* color:{"red","orange","yellow","green","aqua","blue","purple","magenta"})mixer[index++]=float(s.get(std::string(color)+channel)/100);
        std::array<float,12> grade;index=0;for(const auto* wheel:{"Shadow","Midtone","Highlight","Global"})for(const auto* channel:{"Hue","Saturation","Luminance"})grade[index++]=float(s.get(std::string("grade")+wheel+channel)/(std::string_view(channel)=="Hue"?360:100));
        std::vector<float> points;for(const auto& point:s.points)for(double x:{point.hue/360,point.saturation,point.luminance,point.hueShift/100,point.saturationShift/100,point.luminanceShift/100,point.hueRange/360,point.saturationRange,point.luminanceRange}){if(!std::isfinite(x))throw std::runtime_error("Invalid Camera Raw point color");points.push_back(float(x));}
        adjust_camera_raw_curve_color(p,w,h,stride,lut[0].data(),lut[1].data(),lut[2].data(),lut[3].data(),v("refineSaturation")/100,mixer.data(),int(s.points.size()),points.data(),grade.data(),v("gradeBlending")/100,v("gradeBalance")/100,view.pointColor);check();
        adjust_camera_raw_effects(p,w,h,stride,v("texture"),v("clarity"),v("dehaze"),v("glow"),int(v("glowStyle")),v("glowRange"),v("glowSpread"),v("glowWarmth"),v("vignetteAmount"),v("vignetteMidpoint"),v("vignetteRoundness"),v("vignetteFeather"),v("vignetteHighlights"),int(v("vignetteStyle")),scale);if(v("grainAmount")>0)adjust_grain(p,w,h,stride,v("grainAmount"),.5+v("grainSize")/100*19.5,v("grainRoughness"),0x43414d52,0,0,1/scale);check();
    }
    if(!view.clipping){if(view.sharpenMask)adjust_camera_raw_sharpen_mask_overlay(p,w,h,stride,v("sharpenRadius"),v("sharpenDetail"),v("sharpenMasking"),scale);else{
        if(v("removeChromatic")||v("lensProfile")||v("distortion")||v("purpleAmount")||v("greenAmount")||v("opticsVignette"))adjust_camera_raw_optics(p,w,h,stride,int(v("removeChromatic")),int(v("lensProfile")),v("profileDistortion"),v("profileVignetting"),v("distortion")/100*.35+(v("lensProfile")?v("profileDistortion")/100*.35:0),v("purpleAmount"),std::min(v("purpleHueLow"),v("purpleHueHigh")),std::max(v("purpleHueLow"),v("purpleHueHigh")),v("greenAmount"),std::min(v("greenHueLow"),v("greenHueHigh")),std::max(v("greenHueLow"),v("greenHueHigh")),v("opticsVignette"),v("opticsMidpoint"),scale);check();
        if(v("sharpenAmount")||v("noiseLuminance")||v("noiseColor"))adjust_camera_raw_detail(p,w,h,stride,v("sharpenAmount"),v("sharpenRadius"),v("sharpenDetail"),v("sharpenMasking"),v("noiseLuminance"),v("noiseLuminanceDetail"),v("noiseLuminanceContrast"),v("noiseColor"),v("noiseColorDetail"),v("noiseColorSmoothness"),scale);
    }}if(view.shadowOverlay||view.highlightOverlay)adjust_camera_raw_clip_overlay(p,w,h,stride,view.shadowOverlay,view.highlightOverlay);check();rgba_clamp_premultiplied(p,w*h);return Raster::fromRgba(int(w),int(h),p,stride);
}
std::optional<Point> cameraRawWhiteBalance(const Raster& image,std::optional<Point> sample){
    double red=0,green=0,blue=0,count=0;auto linear=[](double x){return x<=.04045?x/12.92:std::pow((x+.055)/1.055,2.4);};auto add=[&](int x,int y){auto p=image.pixel(x,y);if(p.a){red+=linear(p.r/double(p.a));green+=linear(p.g/double(p.a));blue+=linear(p.b/double(p.a));++count;}};if(sample){for(int y=std::max(0,int(sample->y)-2);y<std::min(image.height,int(sample->y)+3);++y)for(int x=std::max(0,int(sample->x)-2);x<std::min(image.width,int(sample->x)+3);++x)add(x,y);}else{int step=std::max(1,int(std::sqrt(double(image.width)*image.height/1000000)));for(int y=0;y<image.height;y+=step)for(int x=0;x<image.width;x+=step)add(x,y);}if(!count)return {};red/=count;green/=count;blue/=count;if(std::min({red,green,blue})<1e-4)return {};const auto a1=.35*red,b1=.15*red+.30*green,c1=green-red,a2=-.35*blue,b2=.15*blue+.30*green,c2=green-blue,det=a1*b2-a2*b1;if(std::abs(det)<1e-8)return {};return Point{std::clamp((c1*b2-c2*b1)/det*100,-100.,100.),std::clamp((a1*c2-a2*c1)/det*100,-100.,100.)};
}
std::string encodeCameraRawSettings(const CameraRawSettings& settings){QJsonObject object;for(const auto& [key,value]:settings.values)object[QString::fromStdString(key)]=value;QJsonArray curves;for(const auto& points:settings.curves){QJsonArray curve;for(const auto& p:points)curve.append(QJsonArray{p.x,p.y});curves.append(curve);}object["curves"]=curves;QJsonArray colors;for(const auto& p:settings.points)colors.append(QJsonArray{p.hue,p.saturation,p.luminance,p.hueShift,p.saturationShift,p.luminanceShift,p.hueRange,p.saturationRange,p.luminanceRange});object["points"]=colors;QJsonArray guides;for(const auto& [a,b]:settings.guides)guides.append(QJsonArray{a.x,a.y,b.x,b.y});object["guides"]=guides;return QJsonDocument(object).toJson(QJsonDocument::Compact).toStdString();}
CameraRawSettings decodeCameraRawSettings(std::string_view json){if(json.size()>65536)throw std::runtime_error("Camera Raw settings exceed budget");const auto doc=QJsonDocument::fromJson(QByteArray(json.data(),qsizetype(json.size())));if(!doc.isObject())throw std::runtime_error("Invalid Camera Raw settings");CameraRawSettings result;auto object=doc.object();for(const auto& p:cameraRawParameters())if(object.contains(p.key))result.set(p.key,object[p.key].toDouble(std::numeric_limits<double>::quiet_NaN()));const auto curves=object["curves"].toArray();if(!curves.isEmpty()){if(curves.size()!=4)throw std::runtime_error("Invalid Camera Raw curve count");for(int c=0;c<4;++c){result.curves[size_t(c)].clear();for(auto point:curves[c].toArray()){auto a=point.toArray();if(a.size()!=2)throw std::runtime_error("Invalid curve point");result.curves[size_t(c)].push_back({a[0].toDouble(),a[1].toDouble()});}if(!effects_tools::validCurve(result.curves[size_t(c)]))throw std::runtime_error("Invalid Camera Raw curve");}}for(auto item:object["points"].toArray()){auto a=item.toArray();if(a.size()!=9||result.points.size()>=32)throw std::runtime_error("Invalid point color");result.points.push_back({a[0].toDouble(),a[1].toDouble(),a[2].toDouble(),a[3].toDouble(),a[4].toDouble(),a[5].toDouble(),a[6].toDouble(),a[7].toDouble(),a[8].toDouble()});}for(auto item:object["guides"].toArray()){auto a=item.toArray();if(a.size()!=4||result.guides.size()>=4)throw std::runtime_error("Invalid upright guide");result.guides.push_back({{a[0].toDouble(),a[1].toDouble()},{a[2].toDouble(),a[3].toDouble()}});}return result;}
}
